<style type="text/css">
    .data .forminputfield {
        margin-left:0px;
    }

    .data td {
        height:42px;
    }

    .delivery {
        display:none;
    }
</style>


<div class="left status_Box" style="background-color:#F1F1F1; margin-right:239px;">
    <div class="data">
        <form id="wholesaler-edit-form">
        <input type="hidden" name="wholesaler[id]" value="<?= $this->escape($this->wholesaler->id); ?>" />
        <input type="hidden" name="wholesaler[is_b2b]" id="wholesaler_is_b2b" value="<?= $this->escape($this->wholesaler->is_b2b); ?>" />
        <table style="width:100%;">
            <tr>
                <td><h4>Naam & Adres</h4></td>
                <td></td>
            </tr>
            <tr>
                <td><?= _t('Company name') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[company_name]" value="<?= $this->escape($this->wholesaler->company_name); ?>" /></td>
            </tr>
            <tr>
                <td style="width:120px;"><?= _t('Voornaam') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[firstname2]" value="<?= $this->escape($this->wholesaler->firstname2); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Achternaam') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[lastname2]" value="<?= $this->escape($this->wholesaler->lastname2); ?>" /></td>
            </tr>
            <tr  id="kvk_wrapper" <?php if(strtolower($this->wholesaler->country)!='nederland') echo 'style="display:none;"'; ?>>
                <td><?= _t('KVK nummer') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[kvk_number]" value="<?= $this->escape($this->wholesaler->kvk_number); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('BTW nummer') ?>:</td>
                <td>
                    <input type="text" class="gray-input" style="width:260px;" name="wholesaler[vat_number]" value="<?= $this->escape($this->wholesaler->vat_number); ?>" />
                    <span style="color:#ff0000; line-height:25px; font-size:15px;" id="wholesaler_vat_status"></span>
                </td>
            </tr>
            <!--
            <tr>
                <td><?= _t('Klantnummer') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[client_number]" value="<?= $this->escape($this->wholesaler->client_number); ?>" /></td>
            </tr>
            -->
            <tr>
                <td><?= _t('Adres') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[address]" value="<?= $this->escape($this->wholesaler->address); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Postcode') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[postcode]" value="<?= $this->escape($this->wholesaler->postcode); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Plaats') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[city]" value="<?= $this->escape($this->wholesaler->city); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Land') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[country]" value="<?= $this->escape($this->wholesaler->country); ?>" /></td>
            </tr>
            <!--<tr>
                <td><?= _t('Kosten categorie') ?>:</td>
                <td>
                    <select name="wholesaler[expense_tag_id]">
                        <?php foreach( $this->expense_tags as $tag ): ?>
                        <option value="<?= $this->escape($tag->id); ?>" <?= $this->wholesaler->expense_tag && $this->wholesaler->expense_tag->id == $tag->id ? 'selected="selected"' : ''; ?>>(<?= $this->escape($tag->number); ?>) <?= $this->escape($tag->name); ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="wholesaler-box purchase_Box">
                    <div class="product">        
                        <ul style="padding-left:58px;">
                            <li class="gap"><?= _t('Aantal') ?></li>
                            <li style="padding-left:10px;padding-right:0px;width:152px;"><?= _t('Omschrijving') ?></li>
                            <li class="gap"><?= _t('BTW') ?></li>
                            <li class="" style="padding-right:13px;"><?= _t('Kort.') ?> %</li>
                            <li style="width:60px;padding-right:13px;"><?= _t('Prijs p/stk') ?></li>
                            <li><?= _t('Totaal excl. btw') ?></li>
                            <li class="last"><?= _t('Categorie') ?></li>
                        </ul>    
                                
                    </div>                       
                    <div id="sortableproducts">           
                        <?php $wholesaler_row_index = 0; ?>
                        <?php foreach( $this->wholesaler->products as $product ): ?>
                        <?= $this->partial('index/new/wholesaler-row.phtml', array('product' => $product, 'products' => $this->products, 'wholesaler_row_index' => $wholesaler_row_index++)); ?>
                        <?php endforeach; ?>                        
                    </div>
                    <input type="hidden" id="wholesaler_row_index" value="<?= $wholesaler_row_index; ?>" />
                    <div class="rule">   
                        <h4 onclick="wholesaler_add_row()" style="cursor:pointer;"><a><?= _t('Inkoop toevoegen') ?></a></h4>
                    </div>
                </td>
            </tr>     -->
            <!--<tr>
                <td><?= _t('Afleveradres') ?>:</td>
                <td style="line-height:29px;">
                    <label class="label_check2">
                    <input type="checkbox" name="delivery" <?= $this->wholesaler->have_delivery ? 'checked="checked"' : '' ?> />
                    </label>
                    &nbsp;&nbsp;
                    <?= _t('Use additional address for delivery') ?>
                </td>
            </tr>
            <tr>
                <td><?= _t('Intracommunautaire Levering') ?>:</td>
                <td style="line-height:29px;">
                    <label class="label_check2">
                    <input type="checkbox" name="is_intro" <?= $this->wholesaler->is_intro ? 'checked="checked"' : '' ?> />
                    </label>
                    &nbsp;&nbsp;
                    Als u deze aanvinkt, zullen alle facturen voor deze klant met een 0% BTW tarief verrekend worden
                </td>
            </tr> -->
            <tr class="delivery">
                <td style="padding-left:30px;"><?= _t('Voornaam') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[delivery_firstname]" value="<?= $this->escape($this->wholesaler->delivery_firstname); ?>" /></td>
            </tr>
            <tr class="delivery">
                <td style="padding-left:30px;"><?= _t('Achternaam') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[delivery_lastname]" value="<?= $this->escape($this->wholesaler->delivery_lastname); ?>" /></td>
            </tr>
            <tr class="delivery">
                <td style="padding-left:30px;"><?= _t('Adres') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[delivery_address]" value="<?= $this->escape($this->wholesaler->delivery_address); ?>" /></td>
            </tr>
            <tr class="delivery">
                <td style="padding-left:30px;"><?= _t('Postcode') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[delivery_postcode]" value="<?= $this->escape($this->wholesaler->delivery_postcode); ?>" /></td>
            </tr>
            <tr class="delivery">
                <td style="padding-left:30px;"><?= _t('Plaats') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[delivery_city]" value="<?= $this->escape($this->wholesaler->delivery_city); ?>" /></td>
            </tr>
            <tr class="delivery">
                <td style="padding-left:30px;"><?= _t('Land') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[delivery_country]" value="<?= $this->escape($this->wholesaler->delivery_country); ?>" /></td>
            </tr>
            <tr>
                <td><h4>Contact gegevens</h4></td>
                <td></td>
            </tr>
            <tr>
                <td><?= _t('E-mailadres') ?></td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[email_address]" value="<?= $this->escape($this->wholesaler->email_address); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Telefoonnummer 1') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[phone1]" value="<?= $this->escape($this->wholesaler->phone1); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Telefoonnummer 2') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[phone2]" value="<?= $this->escape($this->wholesaler->phone2); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('FAX') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[fax]" value="<?= $this->escape($this->wholesaler->fax); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Gsm nummer') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[cellphone]" value="<?= $this->escape($this->wholesaler->cellphone); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Contactpersoon') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[contact_person]" value="<?= $this->escape($this->wholesaler->contact_person); ?>" /></td>
            </tr>
            <tr>
                <td><?= _t('Functie') ?>:</td>
                <td><input type="text" class="gray-input" style="width:260px;" name="wholesaler[role]" value="<?= $this->escape($this->wholesaler->role); ?>" /></td>
            </tr>
            <!--
            <tr>
                <td style="vertical-align: top;"><?= _t('Openingsuren') ?>:</td>
                <td></td>
            </tr>

            <? $days = array(_t('Maandag'), _t('Dinsdag'), _t('Woensdag'), _t('Donderdag'), _t('Vrijdag'), _t('Zaterdag'), _t('Zondag')); ?>
            <?php foreach( $days as $index => $day ): ?>
            <tr>
                <td style="padding-left:20px;">
                    <?= $this->escape($day) ?>
                </td>
                <td>


                    <span style="line-height: 29px;">
                            <input type="text" class="gray-input" style="width:32px;" name="days[<?= $index ?>][0]" value="<?= $this->escape($this->wholesaler->days[$index][0]); ?>" />
                            -
                            <input type="text" class="gray-input" style="width:32px;" name="days[<?= $index ?>][1]" value="<?= $this->escape($this->wholesaler->days[$index][1]); ?>" />
                            <span>
                                <label class="label_check2" style="float:none;display: inline-block;margin-bottom:-1px;">
                                    <input type="checkbox" name="days[<?= $index ?>][2]" <?= !empty($this->wholesaler->days[$index][2]) ? 'checked="checked"' : '' ; ?> />
                                </label>
                                <span style="vertical-align:bottom;"><?= _t('Gesloten') ?></span>
                            </span>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <input type="text" class="gray-input" style="width:32px;" name="days[<?= $index ?>][3]" value="<?= $this->escape($this->wholesaler->days[$index][3]); ?>" />
                            -
                            <input type="text" class="gray-input" style="width:32px;" name="days[<?= $index ?>][4]" value="<?= $this->escape($this->wholesaler->days[$index][4]); ?>" />

                            <span>
                                <label class="label_check2" style="float:none;display: inline-block;margin-bottom:-1px;">
                                    <input type="checkbox" name="days[<?= $index ?>][5]" <?= !empty($this->wholesaler->days[$index][5]) ? 'checked="checked"' : '' ; ?> />
                                </label>
                                <span style="vertical-align:bottom;"><?= _t('Gesloten') ?></span>
                            </span>

                    </span>
                    <br/>
                </td>
            </tr>
            <?php endforeach; ?>
            -->
            <tr>
                <td><?= _t('Extra informatie') ?>:</td>
                <td></td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="wysiwyg gray-input" style="height:120px;width:98%;"><?= Utils::strip_bad_tags($this->wholesaler->info); ?></div>
                    <textarea name="wholesaler[info]" style="padding:10px;width:99%;height:120px;display:none;"><?= $this->escape($this->wholesaler->info); ?></textarea>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <a href="javascript:;" onclick="wholesalers_save_wholesaler();" class="link"><?= _t('Opslaan') ?></a>
                </td>
            </tr>
        </table>
        <br style="clear: both;" />
        </form>
    </div>
</div>

<script type="text/javascript">
    $('.label_check, .label_radio,.label_check2,.label_check3').click(function(){
        setupLabel('#wholesaler-edit-form');
    });
    setupLabel('#wholesaler-edit-form');

    $('[name="wholesaler[info]"]').parent().find('.wysiwyg').bind('hallomodified', function(){
        $('[name="wholesaler[info]"]').val($(this).html().trim());
    }).hallo({
        plugins: {
            'halloformat': {},
            'hallolink': {}
        },
        editable: true
    });

    function wholesalers_init_delivery(checked){
        if( checked ){
           $('.delivery').css('display', 'table-row');
        }else{
           $('.delivery').css('display', 'none');
        }
    }

    $('[name="delivery"]').change(function(){
        wholesalers_init_delivery(this.checked)
    });
    
    $('[name="wholesaler[country]"]').blur(function(){
        if ( $(this).val().toLowerCase() == 'nederland' ) {
            $('#kvk_wrapper').css('display', 'table-row');
        } else {
            $('#kvk_wrapper').css('display', 'none');
        }
    });

    $('[name^=days]').blur(function(){
        if( this.value.match(/^[0-9]{1,2}$/) ){
            this.value = this.value + ':00';
        }
    });
    
    $('[name="wholesaler[vat_number]"]').blur(function(){
        var vat = $(this).val();                                          
        $.post( baseUrl + '/contacts/index/validate-vat', {vat:vat}, function(data) {
            if ( data.is_valid == true ) {
                $('#wholesaler_vat_status').css('color', '#73C83F');
                $('#wholesaler_vat_status').html("Geldig BTW nummer");
                $('#wholesaler_is_b2b').val('1');
            } else {
                $('#wholesaler_vat_status').css('color', '#CC0000');
                $('#wholesaler_vat_status').html("Ongeldig BTW nummer");
                $('#wholesaler_is_b2b').val('0');
            }
        });  
    });

    <?php if( $this->wholesaler && $this->wholesaler->have_delivery ): ?>
        wholesalers_init_delivery(true);
    <?php endif; ?>

</script>