<h2>Overzicht deze week</h2>

<span id="month" style="display: none;">juli</span>

<ul class="name1">
    <li class="first">&nbsp;</li>
    <li>Ma 30/7</li>
    <li>di 31/7</li>
    <li>wo 1/8</li>
    <li>DO 2/8</li>
    <li>VR 3/8</li>
    <li class="color">ZA 4/8</li>
    <li class="last">ZO 5/8</li>
</ul>

<div class="time">

    <ul>
        <li>

            <div class="one">

                07:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                08:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li class="selected">

            <div class="one">

                09:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                10:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                11:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                12:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                13:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                14:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                15:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                16:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                17:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                18:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                19:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                20:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                21:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                22:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li>

            <div class="one">

                23:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
        <li class="last">

            <div class="one">

                0:00

            </div>

            <div class="two">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">

                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three gap">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

            <div class="three">


                <div class="up">

                </div>

                <div class="down">

                </div>

            </div>

        </li>
    </ul>
    
    <div style="display: none;">
        <div class="add-date">
            <div class="inner">
                <div class="middle">
                    <form>
                        <fieldset>
                            <a href="javascript:;" class="add-date-close" onclick="$('.add-date').parent().hide();">X</a>
                            <h5>Afspraak toevoegen</h5>
                            <div class="date-item"><cite>Wanneer:</cite>13 juli</div>
                            <div class="date-field"><cite>Wat:</cite><input type="text" value="bijv.: afspraak met K. de Vries" onblur="if (this.value=='') this.value=this.defaultValue" onclick="if (this.defaultValue==this.value) this.value=''" /></div>
                            <div class="btns">
                                <input type="button" value="Extra opties" class="fancybox" id="various10" href="#lightbox10" />
                                <input type="submit" value="Voeg toe" />
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
</div>