<div class="left">
    <div id="pane1">
        <div class="scroll-pane">
        <ul style="padding-top:5px;">
            <?php $last_letter = null; ?>
            <?php
                foreach($this->employees as $employee){
                    $groups = array('employee-group-0');
                    foreach( $employee->groups as $group ){
                        $groups[] = 'employee-group-' . $group->id;
                    }
            ?>
            <li class="searchable <?= implode(' ', $groups); ?>">
                <a href="javascript:;" onclick="employees_view_employee(<?= $this->escape($employee->id) ?>);">
                    <?php echo $this->escape($employee->lastname) ?>, <?= $this->escape($employee->firstname) ?> <span><?= $this->escape($employee->role) ?></span>
                </a>
                <?php
                    $this_letter = iconv_substr($employee->lastname, 0, 1, 'UTF-8');
                    if( $last_letter != $this_letter ){
                        $last_letter = $this_letter;
                        echo '<div class="digit"><span class="word">', $this->escape($this_letter), '</span></div>';
                    }
                ?>
            </li>
            <?php } ?>
            <li class="no-employees" style="display:none;line-height:50px;text-align:center;font-weight:bold;border-top-color:transparent;padding:0px;width:100%;"><?= _t('No employees found!') ?></li>
        </ul>
        </div>
    </div>
</div>