<html>
	<head>
		<title><?= $this->title ?></title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		
		<style type="text/css">
		body {
			width:800px;
			font-family: DejaVuSans, Tahoma, Verdana;
			font-size: 12px;
			padding:0px;
			margin:auto;
			color: #333;
		}		
        th {
            font-weight: bold;
        }
		table td {
            border: medium none;
            padding: 0 5px;
            margin: 0;
		}        
        table td h1 {
            font-size: 18px;
            line-height: 50px;
            font-weight: bold;
            margin: 0;
            /*text-transform: uppercase;*/
        }        
        table td h3 {
            font-size: 16px;
            /*line-height: 40px;*/
            font-weight: bold;
            margin: 0;
        }        
        table td.result_title {
            font-size: 18px;
            font-weight: bold;
        }        
        td span.right {
            color: #008000;
        }
        td span.wrong {
            color: #FF0000;
        }
		
		</style>
	</head>
  <body>
    <h1>BTW AANGIFTE NAKIJKEN/TESTEN</h1>
    <table style="width:100%;" cellpadding="0" cellspacing="0">
        <tr>
            <td align="left"><b>Status</b></td>
            <td align="left"><b>Berekening</b></td>
            <td align="center"><b>Berekende uitkomst</b></td>
            <td align="center"><b>Waarde in aangifte</b></td>
        </tr>
        <tbody>
            <tr><td colspan="4">&nbsp;</td></tr>
        <?php 
            $value = ($this->result['00']['total_excl_vat'] + $this->result['01']['total_excl_vat'] + $this->result['02']['total_excl_vat'] + $this->result['03']['total_excl_vat'])*0.21; 
            $img = $value >= $this->result['54']['total_excl_vat'] ? 'right' : 'wrong';
            $color = $img=='right' ? 'color: #008000;' : 'color: #FF0000;';
        ?>
            <tr>
                <td rowspan="2" align="center">
                    <img src="<?=$this->baseUrl(); ?>/images/<?=$img?>.png" />
                </td>
                <td>Formule --> ((00)+(01)+(02)+(03)) x 21%</td>
                <td align="right">&nbsp;</td>
                <td align="center">Veld (54)</td>
            </tr>
            <tr>
                <td>Waardes --> ((&euro;<?=Utils::numberFormat($this->result['00']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['01']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['02']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['03']['total_excl_vat'])?>)) x 21%</td>
                <td align="right" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($value)?></b></td>
                <td align="center" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($this->result['54']['total_excl_vat'])?></b></td>
            </tr>
            <tr><td colspan="4">&nbsp;</td></tr>
        <?php 
            $value = $this->result['86']['total_excl_vat']*0.21; 
            $img = $value >= $this->result['55']['total_excl_vat'] ? 'right' : 'wrong';
            $color = $img=='right' ? 'color: #008000;' : 'color: #FF0000;';
        ?>
            <tr>
                <td rowspan="2" align="center">
                    <img src="<?=$this->baseUrl(); ?>/images/<?=$img?>.png" />
                </td>
                <td>Formule --> (86) x 21%</td>
                <td>&nbsp;</td>
                <td align="center">Veld (55)</td>
            </tr>
            <tr>
                <td>Waardes --> (&euro;<?=Utils::numberFormat($this->result['86']['total_excl_vat'])?>) x 21%</td>
                <td align="right" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($value)?></b></td>
                <td align="center" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($this->result['55']['total_excl_vat'])?></b></td>
            </tr>
            <tr><td colspan="4">&nbsp;</td></tr>
        <?php 
            $value = $this->result['87']['total_excl_vat']*0.21; 
            $img = $value >= $this->result['56']['total_excl_vat'] ? 'right' : 'wrong';
            $color = $img=='right' ? 'color: #008000;' : 'color: #FF0000;';
        ?>
            <tr>
                <td rowspan="2" align="center">
                    <img src="<?=$this->baseUrl(); ?>/images/<?=$img?>.png" />
                </td>
                <td>Formule --> (87) x 21%</td>
                <td>&nbsp;</td>
                <td align="center">Veld (56)</td>
            </tr>
            <tr>
                <td>Waardes --> (&euro;<?=Utils::numberFormat($this->result['87']['total_excl_vat'])?>) x 21%</td>
                <td align="right" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($value)?></b></td>
                <td align="center" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($this->result['56']['total_excl_vat'])?></b></td>
            </tr>
            <tr><td colspan="4">&nbsp;</td></tr>
        <?php 
            $value = ($this->result['81']['total_excl_vat']+$this->result['82']['total_excl_vat']+$this->result['83']['total_excl_vat'])*0.21; 
            $img = $value >= $this->result['59']['total_excl_vat'] ? 'right' : 'wrong';
            $color = $img=='right' ? 'color: #008000;' : 'color: #FF0000;';
        ?>
            <tr>
                <td rowspan="2" align="center">
                    <img src="<?=$this->baseUrl(); ?>/images/<?=$img?>.png" />
                </td>
                <td>Formule --> ((81)+(82)+(83)) x 21%</td>
                <td>&nbsp;</td>
                <td align="center">Veld (59)</td>
            </tr>
            <tr>
                <td>Waardes --> ((&euro;<?=Utils::numberFormat($this->result['81']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['82']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['83']['total_excl_vat'])?>)) x 21%</td>
                <td align="right" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($value)?></b></td>
                <td align="center" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($this->result['59']['total_excl_vat'])?></b></td>
            </tr>
            <tr><td colspan="4">&nbsp;</td></tr>
        <?php 
            $value = ($this->result['81']['total_excl_vat']+$this->result['82']['total_excl_vat']+$this->result['83']['total_excl_vat']+$this->result['86']['total_excl_vat']+$this->result['87']['total_excl_vat'])*0.21; 
            $img = $value >= $this->result['xx']['total_excl_vat'] ? 'right' : 'wrong';
            $color = $img=='right' ? 'color: #008000;' : 'color: #FF0000;';
        ?>
            <tr>
                <td rowspan="2" align="center">
                    <img src="<?=$this->baseUrl(); ?>/images/<?=$img?>.png" />
                </td>
                <td>Formule --> ((81)+(82)+(83)+(86)+(87)) x 21%</td>
                <td>&nbsp;</td>
                <td align="center">Veld (xx)</td>
            </tr>
            <tr>
                <td>Waardes --> ((&euro;<?=Utils::numberFormat($this->result['81']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['82']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['83']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['86']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['87']['total_excl_vat'])?>)) x 21%</td>
                <td align="right" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($value)?></b></td>
                <td align="center" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($this->result['xx']['total_excl_vat'])?></b></td>
            </tr>
            <tr><td colspan="4">&nbsp;</td></tr>
        <?php 
            $value = ($this->result['59']['total_excl_vat']+$this->result['62']['total_excl_vat']+$this->result['64']['total_excl_vat']+$this->result['66']['total_excl_vat'])*0.21; 
            $img = $value >= $this->result['yy']['total_excl_vat'] ? 'right' : 'wrong';
            $color = $img=='right' ? 'color: #008000;' : 'color: #FF0000;';
        ?>
            <tr>
                <td rowspan="2" align="center">
                    <img src="<?=$this->baseUrl(); ?>/images/<?=$img?>.png" />
                </td>
                <td>Formule --> ((59)+(62)+(64)+(66)) x 21%</td>
                <td>&nbsp;</td>
                <td align="center">Veld (yy)</td>
            </tr>
            <tr>
                <td>Waardes --> ((&euro;<?=Utils::numberFormat($this->result['59']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['62']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['64']['total_excl_vat'])?>)+(&euro;<?=Utils::numberFormat($this->result['66']['total_excl_vat'])?>)) x 21%</td>
                <td align="right" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($value)?></b></td>
                <td align="center" style="<?=$color?>"><b>&euro; <?=Utils::numberFormat($this->result['yy']['total_excl_vat'])?></b></td>
            </tr>
        </tbody>
    </table>
		
  </body>
</html>
