<style type="text/css">

    .reports-result {
        width:100%;
    }

    .reports-result td {
        height:28px;
        border-bottom:1px solid #eeeeee;
        vertical-align: middle;
        white-space: nowrap;
        padding-left:10px;
    }

    .reports-result th {
        height:28px;
        vertical-align: middle;
        white-space: nowrap;
        padding-left:10px;
    }

    .reports-result .debit, .reports-result .credit {
        text-align: right;
        padding-right:10px;
        width:100px;
        font-weight: bold;;
    }

    .reports-result .date {
        width:130px;
        text-align:left;
    }

    .reports-result .number {
        width:200px;
        text-align:left;
    }

    .reports-result .info {
        padding:0px;
        margin:0px;
        text-align:left;
    }

    .reports-result td.odd {
        background-color:#fafafa;
    }

    .reports-result td.frst {
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
    }

    .reports-result td.even {
        background-color:#fdfdfd;
    }

    .reports-result td a {
        color:#548C03;
        text-decoration: none;
        font-weight:bold;
    }


    .reports-result .contact {
        text-align:left;
    }

    .reports-result .date {
        text-align:right;
        font-weight:bold;
        padding-right:10px;
        padding-left:10px;
    }

    .reports-result td.sum {
        text-align:right;
        font-weight:bold;
        padding-right:10px;
        padding-left:10px;
    }

    .reports-result td.sum, .reports-result td.sum a {
        color:#8C806E;
    }

    .reports-result td.total {
        font-weight:bold;
        color:#548C03;
        background-color: transparent;
    }

    .reports-result td.empty {
        border-width: 0;
        background-color: transparent;
    }

    .reports-result td.zero, .reports-result td.zero a {
        color:#E0D7CA;
    }

</style>
<!-- START RESULT -->
<div class="result_Box">

    <h2><?= _t('Debiteuren') ?></h2>
    <br/>

    <form action="<?= $this->baseUrl() ?>/reports/index/unpaid-invoices-total" method="get">
        <div style="float:left;margin-right:50px;">
            <select name="period" onchange="$(this).parents('form').submit();">
                <option value="this_month" <?= $this->period == 'this_month' ? 'selected="selected"' : ''; ?>><?= _t('Deze maand') ?></option>
                <option value="this_quarter" <?= $this->period == 'this_quarter' ? 'selected="selected"' : ''; ?>><?= _t('Dit kwartaal') ?></option>
                <option value="this_year" <?= $this->period == 'this_year' ? 'selected="selected"' : ''; ?>><?= _t('Dit jaar') ?></option>
                <option value="all" <?= $this->period == 'all' ? 'selected="selected"' : ''; ?>><?= _t('Alle') ?></option>
            </select>
        </div>

        <?= $this->render('index/_partials/exports.phtml'); ?>
    </form>


    <div class="clear"></div>

    <div class="info">
        <br/>
        <?php if( $this->result['contacts'] ): ?>
        <table class="reports-result">
            <thead>
                <tr>
                    <th class="contact"><?= _t('Debiteur') ?></th>
                    <?php foreach( $this->dates as $date ): ?>
                        <th class="date"><?= $date==0?'':strtolower(date('M Y', $date)) ?></th>
                    <?php endforeach; ?>
                    <th class="date"><?= _t('Ouder') ?></th>
                    <th class="date"><?= _t('Total') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach( $this->result['contacts'] as $result ): ?>
                <tr>
                    <td class="contact ?>"><a href="<?= $this->baseUrl() ?>/reports/index/unpaid-invoices-list?period=<?= $this->escape($this->period); ?>&contact_id=<?= $this->escape($result['contact']['id']); ?>"><?= $this->escape($result['contact']['name']); ?></a></td>
                    <?php foreach( $result['totals'] as $date => $total ): ?>
                        <td class="sum  <?= $total['sum'] ? '' : 'zero'; ?>"><a href="<?= $this->baseUrl() ?>/reports/index/unpaid-invoices-list?period=<?= $date === '-' ? 'all' : $this->escape($date); ?>&contact_id=<?= $this->escape($result['contact']['id']); ?>">&euro; <?= Utils::numberFormat($total['sum']); ?></a></td>
                    <?php endforeach; ?>
                    <td class="sum total <?= $result['total'] ? '' : 'zero'; ?>">&euro; <?= Utils::numberFormat($result['total']); ?></td>
                </tr>
                    <?php endforeach; ?>
                <tr>
                    <td class="total empty"><h3><?= _t('Totaal') ?></h3></td>
                    <?php foreach( $this->result['total']['totals'] as $total ): ?>
                        <td class="sum total empty <?= $total ? '' : 'zero'; ?>">&euro; <?= Utils::numberFormat($total); ?></td>
                    <?php endforeach; ?>
                    <td class="sum total empty <?= $this->result['total']['total'] ? '' : 'zero'; ?>">&euro; <?= Utils::numberFormat($this->result['total']['total']); ?></td>
                </tr>
            </tbody>
        </table>
        <p style="width: 100%; text-align: center; color: #999;">Alle bedragen op deze pagina zijn in EUR en inclusief BTW.</p>
        <?php endif; ?>
    </div>

</div>
<!-- END RESULT	 -->
<script type="text/javascript">

    $(document).ready(function(){
        $('[name="period"]').combobox();
    });

</script>
