<!-- strat the main content area -->

<div class="container">
    
    <div class="eleven columns">
        <div class="my_account">

            <div>
                <h4>Mijn Account</h4>

                <ul>
                    <li><a href="/shop/editaccount">Pas je gegevens aan</a></li>
                    <li><a href="/shop/changepwd">Verander wachtwoord</a></li>
                </ul>
            </div>

            <div>
                <h4>Mijn bestellingen</h4>

                <ul>
                    <li><a href="/shop/order">Bekijk bestelgeschiedenis</a></li>
                </ul>
            </div>

        </div><!--end my_account-->
    </div><!--end eleven-->

</div><!--end container-->
<!-- end the main content area -->