<!-- strat the main content area -->
<?php 
$contact = $this->contact;
$settingModel = new SettingsModel();
$mainColor = SettingsModel::getWebshopMainColor();
?>    
<div class="container">
<?php if ( !empty($this->cart_data) ): ?>
    <div class="sixteen columns">
<form action="/shop/saveorder" method="POST" id="orderForm">
        <div class="box_head">
            <h3>Afrekenen</h3>
        </div><!--end box_head -->

        <div class="checkout_outer">
            <h2>Stap 1 : <span>Inloggen & Registreren</span></h2>
            <div class="checkout_content checkout_option clearfix">
                <div class="not_register">
                    <h6>Indien u nog geen account heeft, registreer!</h6>
                    <p>
                        Hier kunt registreren, zodat u uw zendingen kunt volgen, en uw bestellingen in de gaten houden.
                    </p>
                    <a class="gray_btn" href="/shop/editaccount?from=checkout">Registreer nu!</a>
                </div>
                <div id="login-wrapper">
                <?php if ( $this->logged_in ): ?>
                <br/><br/><br/><br/><br/><br/><a class="red_btn continue" href="#" id="continue1" style="background:<?=$mainColor?>;">Naar stap 2</a>
                <?php else: ?>
                    <h6 style="color: firebrick;" id="err_part"></h6>
                    <h6>Gelieve in te loggen!</h6>
                    <label>
                        <strong>Gebruikersnaam <em>*</em></strong>
                        <input type="text" name="loginuser" id="loginuser" value="" placeholder="">
                    </label>
                    <label>
                        <strong>Wachtwoord <em>*</em></strong>
                        <input type="password" name="loginpass" id="loginpass" value="" placeholder="">
                    </label>
                    <div class="submit">
                        <input id="checkout_login" class="red_btn" type="button" name="submit" value="Inloggen" style="background:<?=$mainColor?>;">
                    </div>
                <?php endif; ?>
                </div>
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->

        <div class="checkout_outer">
            <h2>Stap 2 : <span>Facturatiegegevens</span></h2>
            <div class="checkout_content billing_account clearfix">
                <table>
                    <tr>
                        <td>
                            <strong>Uw bedrijf : </strong>
                        </td>
                        <td class="input">
                            <input name="company" id="company" type="text" value="<?=$contact->company_name?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Voornaam : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input name="firstname" id="firstname" type="text" value="<?=$contact->firstname?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Achternaam : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input name="lastname" id="lastname" type="text" value="<?=$contact->lastname?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong> Straat + nr. : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input type="text" name="address" id="address" value="<?=$contact->address?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Postcode : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input type="text" name="postcode" id="postcode" value="<?=$contact->postcode?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Gemeente : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input type="text" name="city" id="city" value="<?=$contact->city?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Land : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <select class="default" tabindex="1" name="country" id="country" onchange="alert(1);">
                                <option value="">Uw land</option>
                                <option value="Belgie" <?php if ( $contact->country == 'Belgie' ) echo 'selected'; ?>>Belgie</option>
                                <option value="Nederland" <?php if ( $contact->country != 'Belgie' ) echo 'selected'; ?>>Nederland</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><a class="red_btn continue" href="#this" id="continue2" style="background:<?=$mainColor?>;">Naar stap 3</a></td>
                    </tr>
                </table>
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->

        <div class="checkout_outer">
            <h2>Stap 3 : <span>Aflever adres</span></h2>
            <div class="checkout_content billing_account clearfix">
                <table>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <label style="float: none; width: 200px; margin-bottom: 0px; line-height: 28px; cursor: pointer;">
                                <input type="checkbox" name="same_delivery" id="same_delivery" style="margin-right:8px;width:auto;"/> Zelfde gegevens als facturatiegegevens
                            </label>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Uw bedrijf : </strong>
                        </td>
                        <td class="input">
                            <input name="delivery_company" id="delivery_company" type="text" value="<?=$contact->company_name?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Voornaam : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input name="delivery_firstname" id="delivery_firstname" type="text" value="<?=$contact->delivery_firstname?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Achternaam : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input name="delivery_lastname" id="delivery_lastname" type="text" value="<?=$contact->delivery_lastname?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Straat + nr. : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input type="text" name="delivery_address" id="delivery_address" value="<?=$contact->delivery_address?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Postcode : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input type="text" name="delivery_postcode" id="delivery_postcode" value="<?=$contact->delivery_postcode?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Gemeente : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <input type="text" name="city" id="city" value="<?=$contact->city?>" placeholder="">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>Land : <em>*</em></strong>
                        </td>
                        <td class="input">
                            <select class="default" tabindex="1" name="delivery_country" id="delivery_country">
                                <option value="">Uw land</option>
                                <option value="Belgie" <?php if ( $contact->delivery_country == 'Belgie' ) echo 'selected'; ?>>Belgie</option>
                                <option value="Nederland" <?php if ( $contact->delivery_country != 'Belgie' ) echo 'selected'; ?>>Nederland</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><a class="red_btn continue" href="#this" id="continue3" style="background:<?=$mainColor?>;">Naar stap 4</a></td>
                    </tr>
                </table>
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->

        <div class="checkout_outer">
            <h2>Stap 4 : <span>Verzendmethode</span></h2>
            <div class="checkout_content clearfix">
                <div style="padding:20px">
                    <p>Verzendmethode</p>
                    <label style="cursor: pointer;"><input type="radio" name="delivery_method" id="delivery_method" checked value="Verzenden per post">Verzenden per post</input></label><br/>
                    <label style="cursor: pointer;"><input type="radio" name="delivery_method" id="delivery_method" value="Ophalen">Ophalen</input></label><br/><br/>
                    <a class="red_btn continue" href="#this" id="continue4" style="background:<?=$mainColor?>;">Naar stap 5</a>
                </div>
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->

        <div class="checkout_outer">
            <h2>Stap 5 : <span>Betaalmethode</span></h2>
            <div class="checkout_content clearfix">
                <div style="padding:20px">
                    <label style="cursor: pointer;"><input type="radio" name="payment_method" id="payment_method" checked value="Paypal">Paypal</input></label><br/>
                    <label style="cursor: pointer;"><input type="radio" name="payment_method" id="payment_method" value="Mistercash">Mistercash</input></label><br/>
                    <label style="cursor: pointer;"><input type="radio" name="payment_method" id="payment_method" value="iDeal">iDeal</input></label><br/><br/>
                    <a class="red_btn continue" href="#this" id="continue5" style="background:<?=$mainColor?>;">Naar stap 6</a>
                </div>
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->

        <div class="checkout_outer">
            <h2>Stap 6 : <span>Extra informatie</span></h2>
            <div class="checkout_content clearfix">
                <div style="padding:20px">
                    <p>Speciale opmerkingen/Vragen : <br/><textarea id="order_note" name="order_note" style="width:80%"></textarea></p>
                    <a class="red_btn continue" href="#this" id="continue6" style="background:<?=$mainColor?>;">Naar stap 7</a>
                </div>
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->

        <div class="checkout_outer">
            <h2>Stap 7 : <span>Bevestig aankoop</span></h2>
            <div class="checkout_content clearfix">
            <div style="padding:20px">
                <table id="checkout-review-table" style="width:100%;" cellspacing="0">
                    <colgroup>
                        <col>
                        <col width="1">
                        <col width="1">
                        <col width="1">
                        <col width="1">
                    </colgroup>
                    <thead>
                        <tr class="first last">
                            <th rowspan="1">Artikelnaam </th>
                            <th align="center" colspan="1">Prijs</th>
                            <th align="center" rowspan="1">Aantal</th>
                            <th align="center" rowspan="1">BTW</th>
                            <th align="center" colspan="1">Subtotaal</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr class="first">
                            <td colspan="4">Subtotaal</td>
                            <td align="right"><span class="price">&euro;<?php echo Utils::numberFormat($this->total_cost); ?></span></td>
                        </tr>
                        <tr>
                            <td colspan="4">BTW</td>
                            <td align="right">
                                <span class="price">&euro;<?php if ( $this->is_intro == 1 ) { echo "0.00"; } else { echo Utils::numberFormat($this->total_cost*0.21); } ?></span>    
                            </td>
                        </tr>
                        <tr class="last">
                            <td colspan="4">
                                <strong>Totaal</strong>
                            </td>
                            <td align="right">
                                <strong><span class="price">&euro;<?php if ( $this->is_intro == 1 ) { echo Utils::numberFormat($this->total_cost); } else { echo Utils::numberFormat($this->total_cost*1.21); } ?></span></strong>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <?php foreach ( $this->cart_data as $product ): ?>
                        <?php 
                            if ( $product->has_new_price ) {
                                $cost = $product->new_price*(100-$product->new_discount)/100; 
                            } else {
                                $cost = $product->price*(100-$product->discount)/100; 
                            }
                        ?>
                        <tr>
                            <td><h3 class="product-name"><?= $product->name ?></h3></td>
                            <td align="right">
                                <span class="cart-price"><span class="price">&euro;<?php echo Utils::numberFormat($cost);?></span></span>
                            </td>
                            <td algin="center"><?=$product->qty?></td>
                            <td algin="right">
                                <span class="cart-price"><span class="price">&euro;<?php if ( $this->is_intro == 1 ) { echo "0.00"; } else { echo Utils::numberFormat($cost*$product->qty*0.21); }?></span></span>
                            </td>
                            <td algin="right">
                                <span class="cart-price"><span class="price">&euro;<?php echo Utils::numberFormat($cost*$product->qty); ?></span></span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div id="invoice_info" class="order_confirm_view">
                <h5>Factuurgegevens</h5>
                <p><span id="result_company"></span></p>
                <p><span id="result_name"></span></p> 
                <p><span id="result_address"></span></p>
                <p><span id="result_postal_city"></span></p>
                <p><span id="result_country"></span></p>
                <h5>Verzendmethode</h5>
                <p id="result_delivery_method"></p>
            </div>
            <div id="delivery_info" class="order_confirm_view">
                <h5>Aflever adres</h5>
                <p><span id="result_delivery_company"></span></p>
                <p><span id="result_delivery_name"></span></p>
                <p><span id="result_delivery_address"></span></p>
                <p><span id="result_delivery_postal_city"></span></p>
                <p><span id="result_delivery_country"></span></p>
                <h5>Betaalmethode</h5>
                <p id="result_payment_method"></p>
            </div>
            <div style="padding: 20px;">
                <h5>Speciale opmerkingen/vragen</h5>
                <p id="result_order_note"></p>
                <br>
                <label for="include_condition"><input type="checkbox" id="include_condition" name="include_condition" />Include Condition Document</label>
            </div>
            <a class="red_btn" id="confirm_order" style="float:right;margin-bottom:15px;margin-right:20px;background:<?=$mainColor?>;" href="#this">Bevestig aankoop</a>
               
            </div><!--end checkout_content-->
        </div><!--end checkout_outer-->
</form>

    </div><!--end sixteen-->
    <?php else: ?>
    <div class="sixteen columns">
        <input type="button" value="Verder winkelen" name="continue" id="continue_shopping" class="gray_btn">
    </div>
<?php endif; ?>
</div><!--end container-->
<!-- end the main content area -->
<script type="text/javascript" src="<?=$this->baseUrl().'/js/webshop/dropKick/jquery.dropkick-1.0.0.js'?>"></script>
<script type="text/javascript">

    $(document).ready(function(){
        $('#confirm_order').on('click', function(){
            $('#orderForm').submit();
        });
        $('#same_delivery').on('click', function(){
            if ( $(this).prop('checked') ) {
                $('#delivery_company').val($('#company').val());
                $('#delivery_firstname').val($('#firstname').val());
                $('#delivery_lastname').val($('#lastname').val());
                $('#delivery_address').val($('#address').val());
                $('#delivery_city').val($('#city').val());
                $('#delivery_postcode').val($('#postcode').val());
                $('#delivery_country').val($('#country').val());
                $('#dk_container_delivery_country').html($('#dk_container_country').html());
            }
        });
        $('#loginpass').on('keypress', function(event){
            if ( event.keyCode == 13 ) {
                $('#checkout_login').click();
            }
        });
        $('.continue').on('click', function() {
            var idx = $('.continue').index(this);
            $('div.checkout_outer h2').eq(idx).next('div.checkout_content').slideUp();
            $('div.checkout_outer h2').eq(idx+1).unbind('click');
            $('div.checkout_outer h2').eq(idx+1).click(
                function(){
                    $('div.checkout_outer h2').next('div.checkout_content').slideUp();
                    $(this).next('div.checkout_content').slideToggle(300);
                }
            );
            $('div.checkout_outer h2').eq(idx+1).next('div.checkout_content').slideToggle(300);
        });
        $('#continue6').on('click', function(){
            $('#result_company').html($('#company').val());
            $('#result_name').html($('#firstname').val()+' '+$('#lastname').val());
            $('#result_address').html($('#address').val());
            $('#result_postal_city').html($('#postcode').val()+' '+$('#city').val());
            $('#result_country').html($('#country').val());
            $('#result_delivery_method').html($('#delivery_method:checked').val());
            
            $('#result_delivery_company').html($('#delivery_company').val());
            $('#result_delivery_name').html($('#delivery_firstname').val()+' '+$('#delivery_lastname').val());
            $('#result_delivery_address').html($('#delivery_address').val());
            $('#result_delivery_postal_city').html($('#delivery_postcode').val()+' '+$('#city').val());
            $('#result_delivery_country').html($('#delivery_country').val());
            $('#result_payment_method').html($('#payment_method:checked').val());
            
            $('#result_order_note').html($('#order_note').val());
        })
        $('#checkout_login').on('click', function(){
            var usr = $('#loginuser');
            var pwd = $('#loginpass');
            if ( usr.val() == "" ) {
                alert("Gelieve uw gebruikersnaam te geven!");
                usr.focus();
                return;
            }
            if ( pwd.val() == "" ) {
                alert("Gelieve uw wachtwoord te geven!");
                pwd.focus();
                return;
            }
            $.post('/shop/ajaxlogin', {loginuser:usr.val(),loginpass:pwd.val()}).success(function(data){
                if ( data.result == "success" ) {
                    location.reload();
                } else {
                    $('#err_part').html("Login mislukt!");
                }
            });
        });
        window.setTimeout(function() {
        <?php if ( $this->logged_in ): ?>
            $('div.checkout_outer h2').eq(1).click(
                function(){
                    $('div.checkout_outer h2').next('div.checkout_content').slideUp();
                    $(this).next('div.checkout_content').slideToggle(300);
                }
            );
            $('div.checkout_outer h2').eq(1).next('div.checkout_content').slideToggle(300);
        <?php else: ?>
            $('div.checkout_outer h2').eq(0).next('div.checkout_content').slideToggle(300);
        <?php endif; ?>
        }, 1000);
        $('#continue_shopping').on('click', function(){
            document.location.href = '/shop';
        });
    });

</script>