<?php
    $addr_street = SettingsModel::getInvoiceProviderAddressStreet();
    $addr_num = SettingsModel::getInvoiceProviderAddressNum();
    $addr_post = SettingsModel::getInvoiceProviderAddressPost();
    $addr_city = SettingsModel::getInvoiceProviderAddressCity();
    $address = $addr_street.' '.$addr_num.' '.$addr_post.' '.$addr_street;
    $phone = SettingsModel::getInvoiceProviderPhone();
    $email = SettingsModel::getInvoiceProviderEmail();
?>

<!-- strat the main content area -->
    
<div class="container">
    <div class="sixteen columns">

        <div class="sixteen columns alpha">
            <div id="googleMap">
                <iframe width="100%" height="372px" border="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?hl=en&safe=active&q=Industrieweg+22+Lanaken&ie=UTF-8&hq=&hnear=0x47c0c2926716baa1:0x557e00c92e0d0d32,Industrieweg+22,+3620+Lanaken,+Belgium&gl=hk&ei=Cv9LUciSMsPClAXOnYDQDw&ved=0CC0Q8gEwAA&amp;output=embed"></iframe> 
            </div><!--end googleMap-->
        </div><!--end eleven-->
    </div><!--end sixteen-->

    <div class="sixteen columns">

        <div class="eleven columns alpha">
            <div id="contact_form">
                <div class="box_head">
                    <h3>Contacteer ons</h3>
                </div><!--end box_head -->

                <form action="/shop/sendcontact" method="post">

                    <div class="five columns alpha">
                        <input type="text" name="name" value="" placeholder="Uw naam *">

                        <input type="text" name="email" value="" placeholder="Uw e-mail *">
                    </div><!--end five-->

                    <div class="six columns omega">
                        <textarea name="message" placeholder="Uw bericht *"></textarea>
                    </div><!--end six-->

                    <div class="submitForm">
                        <input class="red_btn" type="submit" name="submit" value="Versturen">
                        <p>Velden met een ( * ) zijn verplicht.</p>
                        <div class="clear"></div>
                    </div><!--end submitForm-->

                </form><!--end form-->

            </div><!--end contact_form-->
        </div><!--end eleven-->


        <div class="five columns omega">
            <div id="contact_info">
                <ul>
                    <li class="contact_address">
                        <h6>Adres</h6>
                        <p><?=$address?></p>
                    </li>
                    <li class="contact_email">
                        <h6>E-mail</h6>
                        <p><?=$email?></p>
                    </li>
                    <li class="contact_fax">
                        <h6>Telefoon</h6>
                        <p><?=$phone?></p>
                    </li>
                </ul>
            </div><!--end contact_info-->
        </div><!--end five-->

    </div><!--end sixteen-->

    <div class="sixteen columns">
        <div id="tagLine" class="clearfix">
            <div class="eleven columns">
                <h5>
                    Begin nu <span>met winkelen op onze webshop!</span><br>
                    <small>Waar wacht u nog op? Neem gerust een kijkje in ons online assortiment</small>
                </h5>
            </div>
            <div class="four columns" style="text-align:right; float:right;">
                <a class="red_btn" href="/shop/index">Naar producten!</a>
            </div>
            
        </div><!--end tagLine-->
    </div><!--end sixteen-->


</div><!--end container-->
<!-- end the main content area -->