<?php 
    $settingModel = new SettingsModel();
    $mainColor = SettingsModel::getWebshopMainColor();
?>
<div class="tweleve columns omega">

    <div class="pro_name_price">
        <div class="pro_desc_conent clearfix">
            <h6><?=$this->product->name?></h6>
        <?php if ( $this->product->has_new_price ): ?>
            <h5 style="font-weight:normal;font-size:11px;padding-top:-10px;">&nbsp;(+ &euro;<?=Utils::numberFormat($this->product->new_price*(100-$this->product->new_discount)/100*0.21)?> BTW)</h5>
            <h5>&euro; <?=Utils::numberFormat(($this->product->new_price*(100-$this->product->new_discount))/100)?></h5>
        <?php else: ?>
            <h5 style="font-weight:normal;font-size:11px;padding-top:-10px;">&nbsp;(+ &euro;<?=Utils::numberFormat($this->product->price*(100-$this->product->discount)/100*0.21)?> BTW)</h5>
            <h5>&euro; <?=Utils::numberFormat(($this->product->price*(100-$this->product->discount))/100)?></h5>
        <?php endif; ?>
        </div>
    </div><!--end pro_name_price-->

    <div class="seven columns alpha">
        <div class="product_img">
            <ul id="etalage_style_two">
            <li>
                <?php if ( $this->product->main_img != "" ): ?>
                <a href="<?=$this->product->main_img?>">
                <img class="etalage_thumb_image" src="<?=$this->product->main_img?>" alt="">
                <img class="etalage_source_image" src="<?=$this->product->main_img?>" alt="">
                </a>
                <?php else: ?>
                <a href="<?=$this->baseUrl();?>/images/webshop/etalage_img/image_large.jpg">
                <img class="etalage_thumb_image" src="<?=$this->baseUrl();?>/images/webshop/etalage_img/image_thumb.jpg" alt="">
                <img class="etalage_source_image" src="<?=$this->baseUrl();?>/images/webshop/etalage_img/image_large.jpg" alt="">
                </a>
                <?php endif; ?>
            </li>
            <li>
                <?php if ( $this->product->sub_img1 != "" ): ?>
                <a href="<?=$this->product->sub_img1?>">
                <img class="etalage_thumb_image" src="<?=$this->product->sub_img1?>" alt="">
                <img class="etalage_source_image" src="<?=$this->product->sub_img1?>" alt="">
                </a>
                <?php endif; ?>
            </li>
            <li>
                <?php if ( $this->product->sub_img2 != "" ): ?>
                <a href="<?=$this->product->sub_img2?>">
                <img class="etalage_thumb_image" src="<?=$this->product->sub_img2?>" alt="">
                <img class="etalage_source_image" src="<?=$this->product->sub_img2?>" alt="">
                </a>
                <?php endif; ?>
            </li>
            <li>
                <?php if ( $this->product->sub_img3 != "" ): ?>
                <a href="<?=$this->product->sub_img3?>">
                <img class="etalage_thumb_image" src="<?=$this->product->sub_img3?>" alt="">
                <img class="etalage_source_image" src="<?=$this->product->sub_img3?>" alt="">
                </a>
                <?php endif; ?>
            </li>
            </ul>
            <div id="hidden"><div id="zoom"></div></div>
        </div><!--end product_img-->
    </div><!--end six-->
    
    <div class="five columns omega">
        <div class="product_desc">

            <div class="pro_desc_conent">
                <div class="pro_desc_list">
                <ul>
                    <li><strong>Artikel code :&nbsp;</strong><?=$this->product->article_code?></li>
                    <li><strong>Artikel status :&nbsp;</strong><?php if ( $this->product->status == 'active' ) { echo 'Op voorraad'; } else { echo 'Tijdelijk uitverkocht'; }?></li>
                <?php if ( $this->product->has_new_price ): ?>
                    <li><strong>Normale verkoopsprijs :&nbsp;</strong>&euro;<?=Utils::numberFormat($this->product->new_price)?>/st</li>
                    <li><strong>Aanbiedings prijs :&nbsp;</strong>&euro;<?php echo Utils::numberFormat(($this->product->new_price*(100-$this->product->new_discount))/100); ?>/st</li>
                <?php else: ?>
                    <li><strong>Normale verkoopsprijs :&nbsp;</strong>&euro;<?=Utils::numberFormat($this->product->price)?>/st</li>
                    <li><strong>Aanbiedings prijs :&nbsp;</strong>&euro;<?php echo Utils::numberFormat(($this->product->price*(100-$this->product->discount))/100); ?>/st</li>
                <?php endif; ?>
                </ul>
                </div><!--end pro_desc_list-->

                <div class="inputs clearfix">
                    <form id="add_cart_form" method="post" action="/shop/addcart" class="clearfix">
                        <input type="hidden" name="product_id" value="<?=$this->product->id?>" />
                        <label>
                        <select id="qty" name="qty" class="default" tabindex="1">
                            <option value="">--- Kies aantal ---</option>
                            <?php for ($i=0; $i<30; $i++): ?>
                            <option value="<?=$i?>"><?=$i?></option>
                            <?php endfor; ?>
                        </select>
                        </label>

                    </form><!--end form-->

                    <ul class="pro_buttons">
                        <li><input type="button" class="red_btn" value="Toevoegen aan winkelwagen" id="btn_add_cart" style="width:100%;background:<?=$mainColor?>;"/></li>
                    </ul>

                </div><!--end inputs-->
            </div>

        </div><!--end product_desc-->
    </div><!--end six-->

</div><!--end twelve-->


<div class="twelve columns omega">

    <div class="product_info_acc">

        <div class="twelve columns alpha">
            <div class="product_info">

                <h6>Product informatie</h6>
                <div class="acc">
                    <h4>Lange beschrijving</h4>
                    <p><?= $this->escape($this->product->long_description) ?></p>
<!--
                    <h4>Prijsbepaling</h4>
                    <p>Productgroep : <span><?= $this->escape($this->group_name); ?></span></p>
                    <p>Status : <span><?= $this->product->isActive() ? 'Actief' : 'Inactief' ?></span></p>
                    <p>Kost : <span>&euro; <?= Utils::numberFormat($this->product->cost_price) ?> - per stuk</span></p>
                    <p>BTW : <?php
                            $autovat = $this->product->income_tag ? $this->product->income_tag->vat : null;
                            $autovat = !$autovat && $this->product->income_tag && $this->product->income_tag->category ? $this->product->income_tag->category->vat : $autovat;
                            $autovat = !$autovat ? '' : ' (' . $autovat . '%)';
                            ?>
                            <span><?= ($this->product->vat ? $this->escape($this->product->vat) . '%' : _t('By category') . $autovat) ?></span></p>
                    <p>Minimum prijs : <span>&euro; <?= Utils::numberFormat($this->product->min_price) ?> - <?= _t('per stuk') ?></span></p>
                    <p>Korting : <span><?= $this->escape($this->product->discount) ?>%</span></p>
                    <p>Verkoopprijs : <span>&euro; <?= Utils::numberFormat($this->product->price) ?> - <?= _t('per stuk') ?></span></p>
                    <p>Gewicht : <span><?= Utils::generalFormat($this->product->weight, '', '', null, '', 'left', '%.1f'); ?> <?= _t('kg') ?></span></p>-->
                </div> 

            </div><!--end product_info-->
        </div><!--end six-->

    </div><!--end product_info_acc-->

</div><!--end twelve-->

<script type="text/javascript">

    $(document).ready(function(){
        $('#btn_add_cart').on('click', function(){
            $('#add_cart_form').submit();
        });
    });

</script>
<script src="/js/webshop/dropKick/jquery.dropkick-1.0.0.js" type="text/javascript"></script>
