<?php include(APPLICATION_PATH . '/layouts/settings-sidebar.phtml'); ?>
<div id="right">
    <!-- START OVERVIE -->
    <div class="oerview_Box1">
        <h2><?= _t('Secret') ?></h2>

        <div class="opties_Box" style="padding:0px;min-height:inherit;height:auto;">
            <br/>
            <form action="" method="post" style="width:190px;">
                <label style="line-height:29px;"><?= _t('Secret') ?>:</label>
                <br style="clear:both;" />
                <?php if( $this->error ): ?>
                <label><div style="width:200px;color:#ff0000;font-weight:bold;"><?= $this->escape($this->error); ?></div></label>
                <br style="clear:both;" />
                <?php endif; ?>
                <label><input type="password" class="gray-input" name="secret" style="width:160px;" /></label>
                <br style="clear:both;" />
                <div style="text-align:center;">
                <input type="submit" class="green-button" value="Login" />
                </div>
            </form>
        </div>
    </div>
</div>