<div class="bottomWidnow">
        
        <span class="bottomwinbtn botnlief"><img src="<?= $this->baseUrl(); ?>/images/footer-stock-img.png" alt="" /></span>
        
        <!-- START CONTENT -->
        <div class="vries-Box" style="display: none;">
                    
            <form action="#">
                <fieldset>
                    
                    <span class="link bottomwinbtn">edit</span>
                    
                    <div class="vries">
                        <div class="bg" style="padding: 10px;border-radius:5px;">
                            <?php foreach( $this->products as $product ): ?>
                                <p style="color:#ff0000;font-weight:bold;"><?= _t('Product "%s" heeft zonet het minimale aantal in voorraad bereikt! Nog maar %s aanwezig!', array('<a style="text-decoration:none;color:#548C03;" href="' . $this->baseUrl() . '/stock/index/?product_id=' . $product->id . '">' . $this->escape($product->name) . '</a>',$product->stock, $product->min_stock)) ?></p>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </fieldset>
            </form>
        
        </div>
        <!-- END CONTENT -->  
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $(".vries-Box").toggle();
    });
</script>
