<div style="display: none;">
    <div id="tags-category-dialog" class="betalingen-Box" style="width:300px;overflow:auto;">
        <form id="tags-category-form">
            <input type="hidden" name="tag_category[id]" />
            <fieldset>
                <h2><?= _t('New category') ?></h2>
            </fieldset>
            <div class="center">
                <div class="first">
                    <h3><?= _t('Category') ?>:</h3>
                    <div style="height:6px;"></div>
                    <input type="text" name="tag_category[name]" style="width:280px;" class="gray-input" value="Category name" onfocus="if(this.value=='Category name') this.value='';" onblur="if(this.value=='') this.value='Category name';" />
                </div>
                <div style="height:12px;"></div>
                <div class="first">
                    <h3><?= _t('BTW') ?>:</h3>
                    <div style="height:6px;"></div>
                    <input type="text" name="tag_category[vat]" style="width:280px;" class="gray-input" />
                </div>
                <div style="height:12px;"></div>
                <div class="first">
                    <h3><?= _t('Type') ?>:</h3>
                    <div style="height:6px;"></div>
                    <select name="tag_category[type]">
                        <option value="<?= $this->escape(TagCategoryModel::TYPE_INVOICE); ?>"><?= _t('Invoice') ?></option>
                        <option value="<?= $this->escape(TagCategoryModel::TYPE_PURCHASE); ?>"><?= _t('Purchase') ?></option>
                        <option value="<?= $this->escape(TagCategoryModel::TYPE_OTHER); ?>"><?= _t('Other') ?></option>
                        <option value="<?= $this->escape(TagCategoryModel::TYPE_TEMPORARY); ?>"><?= _t('Temporary') ?></option>
                    </select>
                </div>
                <input type="submit" class="button" value="<?= _t('Opslaan') ?>">
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $('[name="tag_category[type]"]').combobox();
</script>