<div style="display: none;">
    <?= $this->escape($this->purchase->id); ?>
    <div class="opslaan-Box overlaybox" id="add-attachment-dialog">
        <form id="purchase-attachment-form" action="<?= $this->baseUrl() . '/purchases/index/create-attachment-purchase'; ?>" enctype="multipart/form-data" method="post">
            <input type="hidden" name="id" value="<?= $this->escape($this->purchase->id); ?>" />
            <input type="hidden" name="edit" value="<?= $this->escape($this->edit); ?>" />
            <fieldset>
                <div class="opslaan selected">
                    <div class="right">

                        <h3><?= _t('Bijlage toevoegen') ?></h3>
                        <p>-- need text here ---</p>

                        <div>
                            <div class="center">
                                <label><?= _t('File') ?>:</label> <input type="file" name="attachment" class="field" value="" />
                            </div>
                            <p><?= _t('File types') ?>: <?= implode(', ', SettingsModel::getPurchaseAttachmentTypes()); ?>
                                <br/>
                                <?= _t('File size') ?>: <?= _t('max') ?> <?= ini_get('upload_max_filesize') ?></p>
                        </div>
                    </div>

                </div>

                <input type="submit" class="button gap button-loader"	value="<?= _t('Creëren') ?>" />
            </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function(){
        $('#purchase-attachment-form input[type=file]').change(function(){
            $.post( baseUrl + '/purchases/index/validate-attachment-file', {filename:$(this).val()}).error(function(){
                setTimeout( function(){$('#purchase-attachment-form input[type=submit]').attr('disabled', 'disabled').css('opacity', '0.5');}, 0);
            }).success(function(){
                $('#purchase-attachment-form input[type=submit]').removeAttr('disabled').css('opacity', '1');
                log_reload();
            });
        });
    });

</script>
