<div class="bottomWidnow">
        
        <span class="bottomwinbtn botnlief"><img src="<?= $this->baseUrl(); ?>/images/footer-img.png" alt="" /></span>
        
        <!-- START CONTENT -->
        <div class="vries-Box" style="display: none;">
                    
            <form action="#">
                <fieldset>
                    
                    <span class="link bottomwinbtn">edit</span>
                    
                    <div class="vries">
                    
                        <ul>
                            <li class="selected"><a href="#"><span>Kees de Vries</span></a></li>
                            <li><a href="#"><span>Pieter Jongsma</span></a></li>
                            <li><a href="#"><span>Jack Koningsburg</span></a></li>
                            <li class="add"><a href="#"><span>add</span></a></li>
                        </ul>	
                        
                        <div class="bg">
                            
                            <div class="comnt">
								<div id="pane1" class="scroll-pane">
                                                                
                                    <div class="center">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Ik</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                            
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_2.jpg" alt="" class="arrow" />
                                        
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                        
                                    </div>
                                
                                    <div class="center last">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Kees de Vries</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                                
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_btn2.png" alt="" class="arrow" />
                                                
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                    
                                    </div>
                                
                                                                
                                    <div class="center">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Ik</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                            
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_2.jpg" alt="" class="arrow" />
                                        
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                        
                                    </div>
                                
                                    <div class="center last">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Kees de Vries</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                                
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_btn2.png" alt="" class="arrow" />
                                                
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                    
                                    </div>
                                
                                                                
                                    <div class="center">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Ik</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                            
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_2.jpg" alt="" class="arrow" />
                                        
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                        
                                    </div>
                                
                                    <div class="center last">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Kees de Vries</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                                
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_btn2.png" alt="" class="arrow" />
                                                
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                    
                                    </div>
                                
                                                                
                                    <div class="center">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Ik</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                            
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_2.jpg" alt="" class="arrow" />
                                        
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                        
                                    </div>
                                
                                    <div class="center last">
                                    
                                        <div class="left">
                                            
                                            <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                                            
                                            <a href="#" class="link2">Kees de Vries</a>
                                        
                                        </div>
                                        
                                        <div class="right">
                                            
                                            <div class="text">
                                            
                                                <p>Sed tellus sapien, auctor ut luctus vel, laoreet a lacus. Fusce non purus arcu. Phasellus interdum, ante sagittis molestie semper, ipsum ligula auctor sem, vitae molestie erat dui vel diam. Proin nisi felis, pretium.</p>
                                                
                                                <img src="<?= $this->baseUrl(); ?>/images/arrow_btn2.png" alt="" class="arrow" />
                                                
                                            </div>
                                            
                                            <span>5 Juni, 2012 om 18:04 <a href="#" class="link3">Citeer</a></span>
                                            
                                        </div>
                                    
                                    </div>
                                
                                </div>
                            </div>
                            
                            <div class="bottom">
                                                                    
                                <textarea rows="4" cols="5" onblur="if (this.value=='') this.value=this.defaultValue" onclick="if (this.defaultValue==this.value) this.value=''">Type hier uw bericht...</textarea>
                                
                                <input type="button" class="button" value="Versturen" />
                            
                            </div>
                            
                        </div>
                    
                    </div>
                    
                </fieldset>
            </form>
        
        </div>
        <!-- END CONTENT -->  
</div>  
