<div class="leftWidnow">

	<span class="leftWin leftWinBtn"><img src="<?= $this->baseUrl(); ?>/images/left-img.png" alt="" /></span>
	
    <!-- START CONTENT -->
    <div class="employees-Box" id="leftwinbox">
        
        <div class="top">
            
            <span class="close leftWinBtn">close</span>
            
            <h2>Werknemers</h2>
        
        </div> 	
        
        <div class="left">
            
            <ul>
                <li class="icon1"><a href="#"><span>Actief</span></a></li>
                <li class="icon2 selected"><a href="#"><span>Ingelogd</span></a></li>
                <li class="icon3"><a href="#"><span>Tijd registreren</span></a></li>
                <li class="icon4"><a href="#"><span>Inactief</span></a></li>
                <li class="icon5"><a href="#"><span>Overige</span></a></li>
            </ul>	

        </div>
        
        <div class="right">
            
            <div class="text">
                
               <div class="scroll-pane">
                    
                    <ul>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li class="color">
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li class="color">
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li class="color">
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li class="color">
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li class="color">
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li class="color">
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                        <li>
                            <div class="first">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/image.png" alt="" /></a>
                            
                            </div>
                            
                            <div class="second">
                                
                                <h3>Jan de Vries</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Project:</span>	Projectnaam </p>
                                    
                                    <p><span>Start tijd:</span>	12:00	</p>
                                    
                                    <p><span>Bezig:</span>	2 uur</p>
                                
                                </div>
                                
                            </div>
                            
                            <div class="third">
                                
                                <a href="#"><img src="<?= $this->baseUrl(); ?>/images/mail_btn.png" alt="" /></a>                                        
                                    
                            </div>
                        </li>
                    </ul>                
                    
                </div>
                
            </div>
            
        </div>
        
        <div class="clear"></div>

        <span class="btn leftWinBtn">btn</span>
        
    </div>
    <!-- END CONTENT -->	

</div>