<div class="rightWidnow">

	<span class="rightWin rightwinbtn"><img src="<?= $this->baseUrl(); ?>/images/calendar.png" alt="" /></span>

    <!-- START CONTENT -->
    <div class="employees-Box sub" id="rightwinbox" style="display:none">
        
        <div class="top">
            
            <span class="close rightwinbtn">close</span>
            
            <h2>Agenda</h2>
        
        </div> 	
        
        <div class="left">
            
            <ul>
                <li class="icon1"><a href="#"><span>Vandaag</span></a></li>
                <li class="icon2 selected"><a href="#"><span>Deze week</span></a></li>
                <li class="icon3"><a href="#"><span>Deze maand</span></a></li>
                <li class="icon4"><a href="#"><span>Komende maand</span></a></li>
                <li class="icon5"><a href="#"><span>Jaaroverzicht</span></a></li>
            </ul>	

        </div>
        
        <div class="right">
            
            <div class="text">
               <div class="scroll-pane jspScrollable">
                	
                    <ul>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li>
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <a href="#" class="button">Tijd registreren</a>
                            
                            <div class="clear"></div>
                            
                        </li>
                        <li class="color">
    
                            <div class="second">
                                
                                <h3>Projectnaam</h3>
                                
                                <div class="box">
                                    
                                    <p><span>Begin tijd:</span>	2 juni, 12:00 </p>
                                    
                                    <p><span>Toegestane tijd:</span>40 uur</p>
                                    
                                </div>
                                
                            </div>
                            
                            <span class="button">Tijd registreren</span>
                            
                        </li>
                    </ul>
                
                </div>	                
            </div>
            
        </div>
        
        <div class="clear"></div>
        
        <span class="btn rightwinbtn">btn</span>
        
    </div>
    <!-- END CONTENT -->

</div>