<!-- START LEFT -->
<div id="left">

    <!-- START NEWS -->
    <div class="news_Box">

        <h2>Instellingen</h2>

        <ul>
            <li><a class="bg2 sub" href="<?= $this->baseUrl() ?>/settings/contact/"><span><?= _t('Algemeen') ?></span></a></li>
            <!-- <li><a class="bg3 sub" href="#"><span><?= _t('Agenda') ?></span></a></li> -->
            <li><a class="bg1 sub" href="<?= $this->baseUrl() ?>/settings/invoice/"><span><?= _t('Facturen') ?></span></a></li>
            <!-- <li><a class="bg5 sub" href="#"><span><?= _t('Inkoop') ?></span></a></li>
            <li><a class="bg6 sub" href="#"><span><?= _t('Documenten') ?></span></a></li> -->
            <li><a class="bg4 sub" href="<?= $this->baseUrl() ?>/settings/offer/"><span><?= _t('Offertes') ?></span></a></li>
            <li><a class="bg4 last" href="<?= $this->baseUrl() ?>/settings/format/"><span><?= _t('Automatisch nummering') ?></span></a></li>
            <!-- <li><a class="bg1 sub1" href="#"><span><?= _t('Projecten') ?></span></a></li> 
            <li><a class="bg4 sub1" href="#"><span><?= _t('Contacten') ?></span></a></li>-->
            <!--<li><a class="bg5 sub1" href="<?= $this->baseUrl() ?>/settings/employees/"><span><?= _t('Gebruikers') ?></span></a></li>-->
            <!-- <li><a class="bg6 sub1" href="#"><span><?= _t('Urenregistratie') ?></span></a></li>
            <li><a class="bg7" href="#"><span><?= _t('Rapporten') ?></span></a></li> -->
            <!--
            <?php if( Utils::user()->can('settings_tags_view') ): ?>
            <li><a class="bg4" href="<?= $this->baseUrl() ?>/settings/tags/"><span><?= _t('Categorieen') ?></span></a></li>
            <?php endif; ?>
            <li><a class="bg4" href="<?= $this->baseUrl() ?>/settings/activity/"><span><?= _t('Activiteit') ?></span></a></li>-->
            <!--
            <li><a class="bg4" href="<?= $this->baseUrl() ?>/settings/pack/"><span><?= _t('Algemene laadlijst') ?></span></a></li>
            <li><a class="bg4" href="<?= $this->baseUrl() ?>/settings/shop/"><span><?= _t('Webwinkel') ?></span></a></li>
            -->
            <!--<li class="last"><a class="bg3" href="<?= $this->baseUrl() ?>/settings/pdf/"><span><?= _t('Overheids rapporten') ?></span></a></li>-->

        </ul>

    </div>
    <!-- END OPTIES -->

</div>
<!-- END LEFT -->