<?php
    $settingModel = new SettingsModel();
    $empSettingModel = new EmpSettingModel();
    
    $user = new Zend_Session_Namespace('user');
    $emp_id = $user->id;
    $addr_street = $empSettingModel->getValue($emp_id, $settingModel->getInvoiceProviderAddressStreetKey());
    if ( $addr_street == null ) $addr_street = SettingsModel::getInvoiceProviderAddressStreet();
    $addr_num = $empSettingModel->getValue($emp_id, $settingModel->getInvoiceProviderAddressNumKey());
    if ( $addr_num == null ) $addr_num = SettingsModel::getInvoiceProviderAddressNum();
    $addr_post = $empSettingModel->getValue($emp_id, $settingModel->getInvoiceProviderAddressPostKey());
    if ( $addr_post == null ) $addr_post = SettingsModel::getInvoiceProviderAddressPost();
    $addr_city = $empSettingModel->getValue($emp_id, $settingModel->getInvoiceProviderAddressCityKey());
    if ( $addr_city == null ) $addr_city = SettingsModel::getInvoiceProviderAddressCity();
    
    $addr_one = $addr_street.' '.$addr_num;
    $addr_two = $addr_post.' '.$addr_city;
    $btw  = $empSettingModel->getValue($emp_id, $settingModel->getInvoiceProviderBTWKey());
    if ( $btw == null ) $btw = SettingsModel::getInvoiceProviderBTW();
    $cur_year = date('Y');
?>

<style type="text/css">
#report td span {
    font-weight: bold;
}

#report td {
    color: #333;
}
</style>

<table cellspacing="0" id="report" border="0">
    <tr>
        <td colspan="5"><h1>Klantenlisting</h1></td>
    </tr>
    <tr>
        <td width="140px">
            <span><b>Datum :</b></span> 
        </td>
        <td colspan="2"><?php echo "1 Januari $cur_year tot 31 December $cur_year"; ?></td>
        <td><span><b>Bedrijfsgegevens</b></span></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>
            <span><b>Bedrijfsjaar : </b></span>
        </td>
        <td colspan="2"><?=$cur_year?></td>
        <td>Jovado Nv.</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3">&nbsp;</td>
        <td><?=$addr_one?></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2"><span><b>Aantal klanten boven/gelijk aan &euro; 250,00 : </b></span></td>
        <td><?=$this->count?></td>
        <td><?=$addr_two?></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td><span><b>Totaal bedrag : </b></span></td>
        <td colspan="2">&euro; <?= Utils::numberFormat($this->total) ?></td>
        <td>BTW <?=$btw?></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td width="140px">&nbsp;</td>
        <td width="180px">&nbsp;</td>
        <td width="130px">&nbsp;</td>
        <td width="140px">&nbsp;</td>
        <td width="140px">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="5">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2"><span><b>Klant</b></span></td>
        <td width="130px"><span><b>BTW NUMMER</b></span></td>
        <td width="140px" align="right"><span><b>Bedrag Excl.BTW</b></span></td>
        <td width="140px" align="right"><span><b>Bedrag Incl.BTW</b></span></td>
    </tr>
    <tr>
        <td colspan="5">&nbsp;</td>
    </tr>
    <?php if( $this->result ): ?> 
     <?php foreach( $this->result as $row ): ?>
    <tr>
        <td colspan="2"><?=$row['contact_name']?></td>
        <td><?=$row['vat_number']?></td>
        <td align="right">&euro; <?= Utils::numberFormat($row['vat_sum']) ?></td>
        <td align="right">&euro; <?= Utils::numberFormat($row['total_sum']) ?></td>
    </tr>
        <?php endforeach; ?>  
     <?php endif; ?>   
</table>