<style type="text/css">

    #content {
        width:530px;
        padding:20px;
        margin:auto;
        background: none repeat scroll 0 0 #F1F1F1;
         border-radius: 5px 5px 5px 5px;
    }

    
    h2 {
        background: linear-gradient(to bottom, #E5E5E5 0%, #D4D4D4 100%) repeat scroll 0 0 transparent;
        border-radius: 3px 3px 3px 3px;
        color: #777777;
        font-family: 'LatoBold';
        font-size: 13px;
        font-weight: normal;
        line-height: 30px;
        padding-left: 10px;
    }


    form .green-button {
        background: url("/images/green-button.png") no-repeat scroll left top transparent;
        border: medium none;
        color: #407424;
        cursor: pointer;
        font-family: 'LatoBold';
        font-size: 13px;
        height: 30px;
        margin: 25px 0 0 1px;
        width: 124px;
    }

    #register form label {
        display: block;
        line-height: 32px;
        margin-bottom: 5px;
    }

    #register form label.l-left {
        
    }

    #register form label.l-right {
        float:right;
    }

    #register form span.label {
        display: inline-block;
        color: #8C806E;
        font-family: Arial;
        font-size: 12px;
        width: 130px;
    }

    #register form span input {
        width: 130px;
    }
    
    #register form span.validation {
        color:#CC0000;
        font-weight:bold;
        margin:10px;    
    }
    
    #register form span.good {
        color: #73C83F;
    }


</style>
<div id="register" style="width:530px;margin:auto;">
    <h2><?= _t('Registratie') ?></h2>
    <br/>
    <div style="margin: 10px;">
    <div style="color:#ff0000;font-weight:bold;margin:10px;margin-left:0px;" id="err_div">
        <?php if( $this->error ): ?>
        <?= $this->escape($this->error); ?>
        <?php endif; ?>
    </div>
    <form method="post" id="registerForm">
        <input type="hidden" name="user[id]" value="<?=$this->id?>" />
        <label class="l-left">
            <span class="label"><?= _t('Bedrijfsnaam') ?>:</span>
            <span><input type="text" val="noempty" name="user[company]" class="gray-input" value="<?= $this->escape($this->company); ?>" /></span>
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('Voornaam') ?>:</span>
            <span><input type="text" val="noempty" name="user[firstname]" class="gray-input" value="<?= $this->escape($this->firstname); ?>" /></span>
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('Achternaam') ?>:</span>
            <span><input type="text" val="noempty" name="user[name]" class="gray-input" value="<?= $this->escape($this->name); ?>" /></span>
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('E-mail') ?>:</span>
            <span><input type="text" val="email" name="user[email]" class="gray-input" value="<?= $this->escape($this->email); ?>" /></span>
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('Username') ?>:</span>
            <span><input type="text" val="noempty" name="user[username]" class="gray-input" value="<?= $this->escape($this->username); ?>" /></span>
            <input type="button" id="check_exist" value="Beschikbaarheid nakijken" />
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('Wachtwoord') ?>:</span>
            <span><input type="password" val="6over" id="userpwd" name="user[password]" class="gray-input" /></span>
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('Herhaal wachtwoord') ?>:</span>
            <span><input type="password" val="6over" id="repeatpwd" name="repeat" class="gray-input" /></span>
            <span class="validation"></span>
        </label>
        <div style="text-align: center;">
         <!--   <input type="button" class="green-button" value="Inloggen" onclick="document.location.href='/login'">-->
            <input type="button" value="<?= _t('Registreer') ?>" class="green-button" onclick="validate()"/>
        </div>
    </form>
    </div>

</div>

<script type="text/javascript">
function validate() {
    var frm = document.getElementById('registerForm');
    if ( document.getElementById('userpwd').value != document.getElementById('repeatpwd').value ) {
        document.getElementById('err_div').innerHTML = "Wachtwoorden komen niet overeen";
        return;
    }
    if ( document.getElementById('userpwd').value.length < 6 ) {
        document.getElementById('err_div').innerHTML = "Uw wachtwoord moet minimaal 6 tekens zijn!";
        return;
    }
    frm.submit();
}

function validateEmail(sEmail) {
    var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
    if (filter.test(sEmail)) {
        return true;
    }
    else {
        return false;
    }
}

$(document).ready(function(){
    $('#register label.l-left input').each(function(idx, obj){
        $(obj).on('blur', function(){
            var type = $(this).attr('val');
            $(this).parent().parent().find('span.validation').removeClass('good');
            
            if ( $(this).val() == '' ) {                              
                $(this).parent().parent().find('span.validation').html('Dit veld mag niet leeg zijn!');
            } else if ( type == "email" ) {
                if ( !validateEmail($(this).val()) ) {
                    $(this).parent().parent().find('span.validation').html('Ongeldig e-mailadres!');
                } else {
                    $(this).parent().parent().find('span.validation').addClass('good');
                    $(this).parent().parent().find('span.validation').html('V');
                }
            } else if ( type == '6over' ) {
                if ( $(this).val().length < 6 ) {
                    $(this).parent().parent().find('span.validation').html('Wachtwoord moet minimaal 6 tekens zijn!');
                } else if( $('#userpwd').val() != $('#repeatpwd').val() ) {
                    $(this).parent().parent().find('span.validation').html('Wachtwoorden komen niet overeen!');
                } else {
                    $('#userpwd').parent().parent().find('span.validation').addClass('good');
                    $('#repeatpwd').parent().parent().find('span.validation').addClass('good');
                    $('#userpwd').parent().parent().find('span.validation').html('V');
                    $('#repeatpwd').parent().parent().find('span.validation').html('V');
                }
            }else {
                if ( $(this).attr('name') == 'user[username]' ) {                      
                    //$(this).parent().parent().find('span.validation').html('Did not check yet!');
                    //$('#check_exist').css('display', 'inline');
                } else {
                    $(this).parent().parent().find('span.validation').addClass('good');
                    $(this).parent().parent().find('span.validation').html('V');
                }
            }
        });
        $(obj).on('keyup', function(event) {
            /*if ( event.keyCode == 9 ) {
                var type = $(this).attr('val');
                $(this).parent().parent().find('span.validation').removeClass('good');
                
                if ( $(this).val() == '' ) {                              
                    $(this).parent().parent().find('span.validation').html('Dit veld mag niet leeg zijn!');
                } else if ( type == "email" ) {
                    if ( !validateEmail($(this).val()) ) {
                        $(this).parent().parent().find('span.validation').html('Ongeldig e-mailadres!');
                    } else {
                        $(this).parent().parent().find('span.validation').addClass('good');
                        $(this).parent().parent().find('span.validation').html('V');
                    }
                } else if ( type == '6over' ) {
                    if ( $(this).val().length < 6 ) {
                        $(this).parent().parent().find('span.validation').html('Wachtwoord moet minimaal 6 tekens zijn!');
                    } else if( $('#userpwd').val() != $('#repeatpwd').val() ) {
                        $(this).parent().parent().find('span.validation').html('Wachtwoorden komen niet overeen!');
                    } else {
                        $('#userpwd').parent().parent().find('span.validation').addClass('good');
                        $('#repeatpwd').parent().parent().find('span.validation').addClass('good');
                        $('#userpwd').parent().parent().find('span.validation').html('V');
                        $('#repeatpwd').parent().parent().find('span.validation').html('V');
                    }
                }else {
                    if ( $(this).attr('name') == 'user[username]' ) {                      
                        //$(this).parent().parent().find('span.validation').html('Did not check yet!');
                        //$('#check_exist').css('display', 'inline');
                    } else {
                        $(this).parent().parent().find('span.validation').addClass('good');
                        $(this).parent().parent().find('span.validation').html('V');
                    }
                }
            }   */
        });
    });
    
    $('#check_exist').on('click', function(){
        if ( $('[name="user[username]"]').val() == "" ) return;
        $.post("/register/check-exist", {username: $('[name="user[username]"]').val()}).success(function(data){
            $('[name="user[username]"]').parent().parent().find('span.validation').removeClass('good');
            if ( data.is_exist == true ) {
                $('[name="user[username]"]').parent().parent().find('span.validation').html('Gebruikersnaam reeds in gebruik!');
            } else {
                $('[name="user[username]"]').parent().parent().find('span.validation').addClass('good');
                $('[name="user[username]"]').parent().parent().find('span.validation').html('V');
                $('#check_exist').css('display', 'none');
            }
        });
    });
});
</script>