<div style="display: none;">
    <div class="opslaan-Box overlaybox" id="contacts-import-dialog">
        <form id="contacts-import-form" action="<?= $this->baseUrl() . '/contacts/index/import-contacts'; ?>" enctype="multipart/form-data" method="post">
            <fieldset>
                <div class="opslaan selected">
                    <div class="right">

                        <h3><?= _t('Import contacten') ?></h3>

                        <div>
                            <div class="center">
                                <label><?= _t('File') ?>:</label> <input type="file" name="file" class="field" value="" />
                            </div>
                            <p><?= _t('File types') ?>: csv
                                <br/>
                                File size: max <?= ini_get('upload_max_filesize') ?></p>
                                <br/>
                                <a href="<?= $this->baseUrl(); ?>/contacts/index/import-template"><?= _t('Download csv template') ?></a>
                        </div>
                    </div>

                </div>

                <input type="submit" class="button gap button-loader"	value="<?= _t('Importeren') ?>" />
            </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function(){
        $('#contacts-import-form input[type=file]').change(function(){
            $.post( baseUrl + '/contacts/index/validate-file', {filename:$(this).val()}).error(function(){
                setTimeout( function(){$('#contacts-import-form input[type=submit]').attr('disabled', 'disabled').css('opacity', '0.5');}, 0);
            }).success(function(){
                $('#contacts-import-form input[type=submit]').removeAttr('disabled').css('opacity', '1');
            });
        });
    });

</script>