<style type="text/css">
    .ui-combobox {
        width:200px;
        border-width:2px;
    }

    .ui-combobox input {
        width:186px;
    }

    li.no-wholesalers:hover {
        background-color:transparent;
    }
</style>
<!-- START LEFT -->

	<!-- START WORKER -->
	<div class="worker_Box">
		<h2><?= _t('Leverancieren op alfabet') ?></h2>
		<div class="search">
		<form method="post">
			<fieldset>
				<p>
					<input id="search" type="text" onblur="if (this.value == '') {this.value = '<?= _t('Zoek een leverancier') ?>';}" onfocus="if(this.value == '<?= _t('Zoek een leverancier') ?>') {this.value = '';}" value="<?= _t('Zoek een leverancier') ?>" onkeydown="if (event.keyCode == 13) { this.form.submit(); return false; }" class="field" name="searchText"/>
				</p>
				<p>
					<select name="group_id" class="select">
						<option value="0"><?= _t('Selecteer een leveranciergroep') ?></option>
						<?php foreach($this->groups as $group){ ?>
							<option value="<?php echo $this->escape($group->id) ?>"><?php echo $this->escape($group->name) ?></option>
						<?php } ?>						
					</select>					
				</p>
			</fieldset>
		</form> 
		</div>

        <div class="info" id="info">
            <div id="wholesalers">
            <?= $this->partial('index/_partials/wholesalers-list.phtml', array('wholesalers' => $this->wholesalers)); ?>
            </div>
            <div class="right">
                <ul>
                    <?php $letters = array_map('chr', range(ord('A'), ord('Z'))); ?>
                    <?php foreach($letters as $letter ): ?>
                    <li style="width:10px;text-align:center;"><a href="javascript:;" onclick="wholesalers_filter_by_letter('<?= $letter ?>');"><?= $this->escape($letter); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
	</div>
	<!-- END WORKER -->
<!-- END LEFT -->

