<?php 
    $has_permission = SettingsModel::getPermissionPurchase();
?>

<style type="text/css">
    #tabs {
        border-width:0px;
        background:none;
        padding:0px;
    }

    #tabs ul {
        background:none;
        border:none;
    }

    #tabs ul li {
        border:none;
    }

    #tabs ul li.ui-tabs-selected a {
        color:#666666;
        font-weight:bold;
    }

    #tabs ul li.ui-tabs-active a {
        color: #666666;
        -moz-border-radius:  4px 4px 0px 0px;
        border-radius: 4px 4px 0px 0px;
        background: #f1f1f1;
    }

    #tabs .ui-tabs-panel {
        border:none;
    }

    .drop {
        width:300px;
    }

    .drop .ui-combobox {
        width:220px;
    }

    .drop .ui-combobox input {
        width:200px;
    }

</style>
<!-- START RIGHT -->
<div id="right" class="sub">

    <!-- START NEWS -->
    <div class="news_Box" style="position: relative;">
        <div style="background: transparent; position:absolute; width:100%; height:100%; z-index:999;<?php if ( $has_permission ) echo 'display:none;'; ?>" class="permission_overwrapper"></div>
        <?php if( Utils::user()->can('purchase_edit') ): ?>
        <h2><?= _t('Nieuwe inkoop') ?></h2>

        <div class="info">
            <ul>
                <li><a href="<?= $this->baseUrl() . '/' . $this->current_module . '/index/new'; ?>"><span><?= _t('Nieuwe inkoop maken') ?></span></a></li>
                <!-- <li><a class="bg1" href="#"><span>Creditfactuur</span></a></li> -->
            </ul>
        </div>
        <?php endif; ?>

        <?= $this->render('index/_partials/purchase-bulk-sidebar.phtml'); ?>

    </div>

    <?= $this->render('index/_partials/purchases-totals.phtml'); ?>
    <!-- END OPTIES -->

</div>
<!-- END RIGHT -->

<!-- START LEFT -->
<div id="left" class="sub">

    <!-- START OPTIES -->
    <div class="opties_Box">

        <h2><?= _t('Opties') ?></h2>

        <div class="search" style="position: relative;">
        <div style="background: transparent; position:absolute; width:100%; height:100%; z-index:999;<?php if ( $has_permission ) echo 'display:none;'; ?>" class="permission_overwrapper"></div>
        <form id="main-invoice-form" action="" method="get">
            <fieldset class="drop">
                <label><?= _t('Bekijk') ?>:</label>

                <select class="select" name="contact_id" onchange="window.location = baseUrl + '/<?= $this->escape($this->current_module) ?>/index/?contact_id=' + this.value">
                    <option value="0"><?= _t('Selecteer een crediteurengroep') ?></option>
                    <?php foreach( $this->contacts as $contact ): ?>
                    <option <?= $contact->id == $this->contact_id ? 'selected="selected"' : ''; ?> value="<?= $this->escape($contact->id); ?>"><?= $this->escape(trim($contact->firstname2 . ' ' . $contact->lastname2)); ?></option>
                    <?php endforeach; ?>
                </select>

            </fieldset>
            <fieldset class="drop" style="width:520px;">
                <label><?= _t('Inkoopdatum') ?>:</label>
                <select name="date" onchange="$('#main-invoice-form').submit();">
                    <option value="0">Kiezen</option>
                    <option value="last_month" <?= $this->date == 'last_month' ? 'selected="selected"' : ''; ?>><?= _t('Vorige maand') ?></option>
                    <option value="this_month" <?= $this->date == 'this_month' ? 'selected="selected"' : ''; ?>><?= _t('Huidige maand') ?></option>
                    <option value="last_quarter" <?= $this->date == 'last_quarter' ? 'selected="selected"' : ''; ?>><?= _t('Vorige kwartaal') ?></option>
                    <option value="this_quarter" <?= $this->date == 'this_quarter' ? 'selected="selected"' : ''; ?>><?= _t('Huidige kwartaal') ?></option>
                    <option value="last_year" <?= $this->date == 'last_year' ? 'selected="selected"' : ''; ?>><?= _t('Vorig jaar') ?></option>
                    <option value="this_year" <?= $this->date == 'this_year' ? 'selected="selected"' : ''; ?>><?= _t('Huidig jaar') ?></option>
                </select>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="text" onchange="$('#main-invoice-form').submit();" class="gray-input" style="width:68px;text-align: center;height:14px;vertical-align:bottom;" name="date_from" value="<?= $this->date_from; ?>" />
                <a style="line-height:26px;">-</a>
                <input type="text" onchange="$('#main-invoice-form').submit();" class="gray-input" style="width:68px;text-align: center;height:14px;vertical-align:bottom;" name="date_to" value="<?= $this->date_to; ?>" />
            </fieldset>
        </form>
        </div>

        <h2><?= _t('Inkoop overzicht') ?></h2>

        <div id="tabs">
            <ul class="tab" style="padding-left: 0px;">
                <?php foreach( $this->tabs as $key => $tab ): ?>
                <li><a id="tab-<?= $this->escape($key); ?>" onclick="set_active_tab('<?= $this->escape($key); ?>')" href="#<?= $this->escape($key); ?>"><?= $this->escape($tab['label'])?> (<?= $this->escape($tab['total']); ?>)</a></li>
                <?php endforeach; ?>
            </ul>

            <?php foreach( $this->tabs as $key => $tab ): ?>

            <div class="tab-wrapper" id="<?= $this->escape($key) ?>" style="padding:0px;margin:0px;">

                <?php if( $tab['result'] ): ?>
                <div class="info">
                    <span class="price"><?= $this->escape($tab['label']) ?> &nbsp;∙&nbsp; &euro; <?= Utils::numberFormat($tab['sum']); ?></span>
                </div>

                <div class="status" style="padding-bottom:1px;">
                <form id="form-<?= $this->escape($key); ?>" method="get">
                    <input type="hidden" name="pages[<?= $this->escape($key); ?>]" value="<?= $this->escape($tab['page']); ?>" />
                    <input type="hidden" name="date_from" value="<?= $this->escape($this->date_from); ?>" />
                    <input type="hidden" name="date_to" value="<?= $this->escape($this->date_to); ?>" />
                    <input type="hidden" name="date" value="<?= $this->escape($this->date) ?>" />
                    <fieldset>
                        <ul>
                            <li class="gap">
                                <div class="first"><label class="label_check2"><input type="checkbox" class="checkall" /></label></div>
                                <div class="second"><h3><?= _t('Inkoop') ?></h3></div>
                                <div class="third" style="width:80px;"><h3><?= _t('Inkoopdatum') ?></h3></div>
                                <div class="four" style="width:130px;text-align: center;"><h3><?= _t('Inkoop vervaldatum') ?></h3></div>
                                <div class="five"><h3><?= _t('Crediteur') ?></h3></div>
                                <div style="width:90px;text-align:center;"><h3><?= _t('Bedrag') ?></h3></div>
                                <div class="seven"><h3><?= _t('Status') ?></h3></div>
                            </li>
                            <?php foreach( $tab['result'] as $key => $purchase ): ?>
                            <li <?= $key % 2 == 0 ? 'class="color"' : '' ?>>
                                <div class="first"><label class="label_check2"><input type="checkbox" name="purchases[<?= $this->escape($purchase->id); ?>]" value="<?= $this->escape($purchase->id); ?>" /></label></div>
                                <div class="second"><a href="<?= $this->baseUrl(); ?>/purchases/index/view/id/<?= $this->escape($purchase->id); ?>"><?= $this->escape($purchase->number); ?></a></div>
                                <div class="third" style="width:80px;"><?= $this->escape(date(Constants::DATE_FORMAT, $purchase->invoice_time)); ?></div>
                                <div class="four" style="width:110px;margin-left:20px;text-align: left;"><?= $this->escape(date(Constants::DATE_FORMAT, $purchase->expire_time)); ?></div>
                                <div class="five"><a href="/wholesalers?wholesaler_id=<?=$purchase->contact ? $purchase->contact->id : 0?>"><?= $this->escape($purchase->contact ? $purchase->contact->company_name ? $purchase->contact->company_name : $purchase->contact->name : ''); ?></a>&nbsp;</div>
                                <div><div style="width:60px;margin-right:30px;text-align:right;"><nobr>&nbsp;&euro; <?= Utils::numberFormat($purchase->total_sum); ?></nobr></div></div>
                                <div class="seven"><a class="concept <?= $this->escape($purchase->status_color) ?>" href="javascript:;"><?= $this->escape($purchase->status_text) ?></a></div>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </fieldset>

                </form>
                </div>
                <?= $this->paginate($tab['page'], $tab['total'], $tab['per_page'])->html('javascript:result_page({page});'); ?>
                <?php elseif ( $this->is_new ): ?>
                    <div class="info">
                        <span class="price"><?= $this->escape($tab['label']) ?> &nbsp;∙&nbsp; &euro; <?= Utils::numberFormat($tab['sum']); ?></span>
                    </div>

                    <div class="status" style="padding-bottom:1px;">
                    <form id="form-<?= $this->escape($key); ?>" method="get">                           
                    <fieldset>
                    <ul>
                        <li class="gap">
                            <div class="first"><label class="label_check2"><input type="checkbox" class="checkall" /></label></div>
                            <div class="second"><h3><?= _t('Inkoop') ?></h3></div>
                            <div class="third" style="width:80px;"><h3><?= _t('Inkoopdatum') ?></h3></div>
                            <div class="four" style="width:130px;text-align: center;"><h3><?= _t('Inkoop vervaldatum') ?></h3></div>
                            <div class="five"><h3><?= _t('Crediteur') ?></h3></div>
                            <div style="width:90px;text-align:center;"><h3><?= _t('Bedrag') ?></h3></div>
                            <div class="seven"><h3><?= _t('Status') ?></h3></div>
                        </li>
                    </ul>
                    <div style="padding: 15px 2%;">
                        <div style="float: left; width: 66%;">
                            <h3 style="font-size:19px;color:#599506; margin-bottom:10px;">Je eerste inkoop inbrengen!</h3>
                            <span style="font-size:12px;">
                            Naast het maken van facturen en offertes, kunt u nu ook inkopen inbrengen! <br>
                            Op deze manier kunt u echt starten <br>
                            met het maken van een correcte boekhouding.<br><br>
                            Laten we beginnen!
                            </span> <br>
                            <input type="button" class="green-button" name="first-new-invoice" <?php if ( $has_permission ): ?> onclick="window.location.href='/purchases/index/new';" <?php endif; ?> value="Inkoop inbrengen!" style="margin: 10px 0 20px;"/>
                            <input type="button" class="green-button" name="btn-permission-purchase" value="<?php echo !$has_permission ? _t('Module activeren') : _t('Module deactiveren')?>" style="margin: 10px 0 20px 20px;"/>
                        </div>
                        <div style="float: right; width: 25%;">
                            <img src="/images/inkoop.png" width="139px" alt="">
                        </div>
                    </div>
                    </fieldset>
                                            
                    </form>
                    </div>
                <?php endif; ?>

            </div>

            <?php endforeach; ?>
        </div>
    </div>
</div>

<?= $this->partial('index/_partials/purchase-payment/dialog.phtml'); ?>

<script type="text/javascript">

    var active_tab = '<?= $this->escape($this->tab); ?>';
    var active_tab_init = true;

    $(document).ready(function(){
        $('[name=date_from], [name=date_to]').datepicker({dateFormat: "dd-mm-yy"});
        $('#tabs').tabs();
        $('#tab-<?= $this->escape($this->tab); ?>').click();
        $('select[name="contact_id"]').combobox({input_class:'round-drop-down'});
        $('select[name="date"]').combobox({input_class:'round-drop-down'});
        active_tab_init = false;
        
        $('[name=btn-permission-purchase]').on('click', function(){
            $.post(baseUrl + '/purchases/index/permission-update/', {}).success(function(data){
                alert(data.message);
                /*$('[name=btn-permission-purchase]').val(data.button_text);
                if ( data.button_text == "Enable" ) {
                    $('.permission_overwrapper').css('display', 'block');
                    $('[name=first-new-invoice]').unbind('click');
                } else {
                    $('.permission_overwrapper').css('display', 'none');
                    $('[name=first-new-invoice]').on('click', function(){
                        alert("work!");
                        //window.location.href = '/purchases/index/new';
                    });
                } */
                window.location.reload();
            });
        });
    });

    function set_active_tab(tab){
        disable_loader = true;
        active_tab = tab;
        if( active_tab_init == false ){
            $.get(baseUrl + '/purchases/index/active-tab/tab/' + tab);
        }
    }

    function result_page(page){
        $('[name="pages[' + active_tab + ']"]').val(page).parent('form').submit();
    }

    $('[name=date_from],[name=date_to]').attr('placeholder', 'dd-mm-jjjj');

</script>
