<style type="text/css">

    #content {
        width:500px;
        padding:20px;
        margin:auto;
    }

    #forgot form label {
        display: inline-block;
        line-height: 32px;
        margin-bottom: 5px;
    }

    #forgot form label.l-left {
        float:left;
        width: 100%;
    }

    #forgot form label.l-right {
        float:right;
    }

    #forgot form span.label {
        display: inline-block;
        width: 130px;
    }

    #forgot form span input {
        width:130px;
    }
    
    #forgot form span.validation {
        color:#CC0000;
        font-weight:bold;
        margin:10px;    
    }
    
    #forgot form span.good {
        color: #73C83F;
    }


</style>
<div id="forgot" style="width:500px;margin:auto;">
    <h2><?= _t('Password Reset') ?></h2>
    <br/>
    <div style="margin: 10px;">
    <?php if( $this->error ): ?>
    <div style="color:#ff0000;font-weight:bold;margin:10px;margin-left:0px;"><?= $this->escape($this->error); ?></div>
    <?php endif; ?>
    <?php if( $this->msg ): ?>
    <div style="color:#73C83F;font-weight:bold;margin:10px;margin-left:0px;"><?= $this->escape($this->msg); ?></div>
    <?php endif; ?>
    <form method="post">
        <label class="l-left">
            <span class="label"><?= _t('Username') ?>:</span>
            <span><?=$this->username?></span>
        </label>                                                                                          
        <label class="l-left">
            <span class="label"><?= _t('Wachtwoord') ?>:</span>
            <span><input type="password" id="userpwd" name="usrpwd" class="gray-input" /></span>
            <span class="validation"></span>
        </label>
        <label class="l-left">
            <span class="label"><?= _t('Herhaal wachtwoord') ?>:</span>
            <span><input type="password" id="repeatpwd" name="rptpwd" class="gray-input" /></span>
            <span class="validation"></span>
        </label>                                                                                          
        <div style="text-align: center; float: left; width:100%;">
            <input type="button" class="green-button" value="Inloggen" onclick="document.location.href='/login'">
            <input type="submit" value="<?= _t('Save') ?>" class="green-button" />
        </div>
    </form>
    </div>

</div>

<script type="text/javascript">                

function validateEmail(sEmail) {
    var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
    if (filter.test(sEmail)) {
        return true;
    }
    else {
        return false;
    }
}

$(document).ready(function(){
    $('#forgot label.l-left input').each(function(idx, obj){
        $(obj).on('keyup', function(event) {
            var type = $(this).attr('val');
            $(this).parent().parent().find('span.validation').removeClass('good');
            
            if ( $(this).val() == '' ) {                              
                $(this).parent().parent().find('span.validation').html('Dit veld mag niet leeg zijn!');
            } else {
                if ( $(this).val().length < 6 ) {
                    $(this).parent().parent().find('span.validation').html('Wachtwoord moet minimaal 6 tekens zijn!');
                } else if( $('#userpwd').val() != $('#repeatpwd').val() ) {
                    $(this).parent().parent().find('span.validation').html('Wachtwoorden komen niet overeen!');
                } else {
                    $('#userpwd').parent().parent().find('span.validation').addClass('good');
                    $('#repeatpwd').parent().parent().find('span.validation').addClass('good');
                    $('#userpwd').parent().parent().find('span.validation').html('V');
                    $('#repeatpwd').parent().parent().find('span.validation').html('V');
                }
            }
        });
    });       
});
</script>