<?php if( !$this->contact ){
    return;
}
?>
<div class="layoutright">
	<a class="open" href="#">&euro; 0,00 te ontvangen</a>
	<div class="clear"></div>
	<div class="project">
		<ul>
            <?php if( Utils::user()->can('invoice_view') ): ?>
			<li><a href="<?= $this->baseUrl() . '/invoices/?contact_id=' . $this->escape($this->contact->id); ?>"><?= _t('Alle verkoopfacturen') ?> (<?= count($this->contact->finalInvoices); ?>)</a></li>
            <?php endif; ?>
            <?php if( Utils::user()->can('offer_view') ): ?>
			<li><a href="<?= $this->baseUrl() . '/offers/?contact_id=' . $this->escape($this->contact->id); ?>"><?= _t('Alle offertes') ?> (<?= count($this->contact->finalOffers); ?>)</a></li>
            <?php endif; ?>
		</ul>    
		<ul class="gap">
            <?php if( Utils::user()->can('invoice_edit') ): ?>
			<li><a href="<?= $this->baseUrl() . '/invoices/index/new/?contact_id=' . $this->escape($this->contact->id); ?>"><?= _t('Nieuwe factuur') ?></a></li>
            <?php endif; ?>

            <?php if( Utils::user()->can('purchase_edit') ): ?>
			<li><a href="<?= $this->baseUrl() . '/purchases/index/new/?contact_id=' . $this->escape($this->contact->id); ?>"><?= _t('Nieuwe inkoopfactuur') ?></a></li>
            <?php endif; ?>

            <?php if( Utils::user()->can('offer_edit') ): ?>
			<li><a href="<?= $this->baseUrl() . '/offers/index/new/?contact_id=' . $this->escape($this->contact->id); ?>"><?= _t('Nieuwe offerte') ?></a></li>
            <?php endif; ?>

            <?php if( Utils::user()->can('invoice_edit') ): ?>
			<li><a href="#"><?= _t('Nieuwe periodieke factuur') ?></a></li>
            <?php endif; ?>
		</ul>
	</div>
<div id="contact-groups" class="group">
    <?= $this->partial('index/_partials/contact-groups.phtml', array('contact' => $this->contact, 'groups' => $this->groups)); ?>
</div>
<div id="contact-employees" class="group">
    <?= $this->partial('index/_partials/contact-employees.phtml', array('contact' => $this->contact, 'employees' => $this->employees)); ?>
</div>
</div>