<div class="news_Box">
    <h2><?= _t('Overige instellingen') ?></h2>

    <div class="info">

        <div class="info">
            <ul style="padding-bottom: 0px;">
                <!-- PDF -->
                <li class="last"><a class="bg3" id="pdf-bulk-receipt" href="javascript:;"><span><?= _t('Afdrukken') ?></span></a></li>
                <!-- INVOICE -->
                <?php if( Utils::user()->can('stock_receipt_edit') ): ?>
                <li class="last"><a class="bg4" id="pack-bulk-receipt" href="javascript:;"><span><?= _t('Generate packing list') ?></span></a></li>
                <?php endif; ?>
                <!-- INVOICE -->
                <?php if( Utils::user()->can('stock_receipt_edit') ): ?>
                <li class="last"><a class="bg9" id="invoice-bulk-receipt" href="javascript:;"><span><?= _t('Generate invoice') ?></span></a></li>
                <?php endif; ?>
                <!-- DELETE -->
                <?php if( Utils::user()->can('stock_receipt_delete') ): ?>
                <li class="last"><a class="bg5" id="delete-bulk-receipt" href="javascript:;"><span><?= _t('Verwijder bestel bon') ?></span></a></li>
                <?php endif; ?>
            </ul>
        </div>

    </div>
</div>

<script type="text/javascript">

    function receipts_collect_checked(){
        var ids = []
        var checked = $('#tabs div.tab-wrapper:visible input[type=checkbox]:checked');
        for( var i = 0; i < checked.length; i++ ){
            if( checked[i].value > 0 ){
                ids.push({name:'receipts[]', value:checked[i].value});
            }
        }

        return $.param(ids);
    }

    $(document).ready(function(){

        $('#pdf-bulk-receipt').click(function(){
            if( params = receipts_collect_checked() ){
                var form = $($('#form-' + $('#tabs div.tab-wrapper:visible')[0].id));
                form.attr('action', baseUrl + '/stock/receipt/bulk-pdf/');
                form.submit();
            }else{
                alert('<?= _t('Select at least one receipt!') ?>');
            }

        });

        $('#invoice-bulk-receipt').click(function(){
            if( params = receipts_collect_checked() ){
                $.post(baseUrl + "/stock/receipt/invoice/", params);
            }else{
                alert('<?= _t('Select at least one receipt!') ?>');
            }

        });

        $('#pack-bulk-receipt').click(function(){
            if( params = receipts_collect_checked() ){
                $.post(baseUrl + "/stock/receipt/pack/", params);
            }else{
                alert('<?= _t('Select at least one receipt!') ?>');
            }

        });

        $('#delete-bulk-receipt').click(function(){
            if( !confirm('<?= _t('Are you sure?') ?>') ){
                return;
            }

            if( params = receipts_collect_checked() ){
                $.post(baseUrl + "/stock/receipt/delete-bulk/", params);
            }else{
                alert('<?= _t('Select at least one receipt!') ?>');
            }
        })
    });
</script>