<style type="text/css">
	#tabs {
		border-width:0px;
		background:none;
        padding:0px;
	}
	
	#tabs ul {
		background:none;
		border:none;
	}
	
	#tabs ul li {
		border:none;
	}
	
	#tabs ul li.ui-tabs-selected a {
		color:#666666;
		font-weight:bold;
	}

    #tabs ul li.ui-tabs-active a {
        color: #666666;
        -moz-border-radius:  4px 4px 0px 0px;
        border-radius: 4px 4px 0px 0px;
        background: #f1f1f1;
    }
	
	#tabs .ui-tabs-panel {
		border:none;
    }

    .drop {
        width:300px;
    }

    .drop .ui-combobox {
        width:220px;
    }

    .drop .ui-combobox input {
        width:200px;
    }

    .date-filter {
        margin-left:300px;
    }

    .date-filter a {
        color:#548C03;
        font-weight:bold;
        display: inline-block;
        width:100px;
    }

</style>
<!-- START RIGHT -->
<div id="right" class="sub">
    
    <!-- START NEWS -->
    <?php if( ($this->proforma && Utils::user()->can('offer_edit')) || (!$this->proforma && Utils::user()->can('invoice_edit')) ): ?>
    <div class="news_Box">
        <h2><?= _t('Nieuwe') ?> <?= ($this->credit ? _t('Credit-Factuur') : ($this->proforma ? _t('Offerte') : _t('Factuur'))); ?></h2>
        
        <div class="info">
            <ul>
                <li><a href="#" onclick="upload_show();"><span><?= ($this->credit ? _t('Credit-Factuur') : ($this->proforma ? _t('Offerte') : _t('Factuur'))); ?> <?= _t('met bijlage') ?></span></a></li>
                <li><a href="<?= $this->baseUrl() . '/' . $this->current_module . '/index/new'; ?>"><span><?= ($this->credit ? _t('Credit-Factuur') : ($this->proforma ? _t('Offerte') : _t('Factuur'))); ?> <?= _t('zonder bijlage') ?></span></a></li>
                <!-- <li><a class="bg1" href="#"><span>Creditfactuur</span></a></li> -->
            </ul>
        </div>
    </div>
    <br/>
    <?php endif; ?>
    <div class="news_Box">
       	<?= $this->render('index/_partials/invoices-bulk-sidebar.phtml'); ?>
    </div>
    <?= $this->render('index/_partials/invoices-totals.phtml'); ?>
    <br/>
    <?php
        // temporally stopped
        if( false && $this->proforma && Utils::user()->can('offer_edit') ){
            echo '<div class="news_Box">';
            echo $this->render('index/_partials/proforma-status-bulk-sidebar.phtml');
            echo '</div>';
        }
    ?>
    <!-- END OPTIES -->

</div>
<!-- END RIGHT -->

<!-- START LEFT -->
<div id="left" class="sub">

    <!-- START OPTIES -->
    <div class="opties_Box">

        <?php if( $this->credit ): ?>
        <h2><?= _t('Credit facturen overzicht') ?></h2>
        <?php else: ?>
        <h2><?= $this->proforma ? _t('Offertes') : _t('Facturen'); ?> <?= _t('overzicht') ?></h2>
        <?php endif; ?>
        
        <div id="tabs">
	        <ul class="tab" style="padding-left:0px;">
	        	<?php foreach( $this->tabs as $key => $tab ): ?>
	            <li><a id="tab-<?= $this->escape($key); ?>" onclick="set_active_tab('<?= $this->escape($key); ?>')" href="#<?= $this->escape($key); ?>"><?= $this->escape($tab['label'])?> (<?= $this->escape($tab['total']); ?>)</a></li>
	            <?php endforeach; ?>
	        </ul>  
            <?php $invoice_total_count = 0; ?>
	        	        	        
	        <?php foreach( $this->tabs as $key => $tab ): ?>
	        
	        	<div class="tab-wrapper" id="<?= $this->escape($key) ?>" style="padding:0px;margin:0px;">
		        	<?php if( $tab['result'] ): ?>
                        <div class="info" style="margin-bottom:10px;">
                            <span class="price"><?= $this->escape($tab['label']) ?> &nbsp;∙&nbsp; &euro; <?= Utils::numberFormat($tab['sum']); ?></span>
                        </div>

                        <div class="status" style="padding-bottom:1px;">
                        <form id="form-<?= $this->escape($key); ?>" method="get">
		        		<input type="hidden" name="contact_id" value="<?= $this->escape($this->contact_id); ?>" />
		        		<input type="hidden" name="pages[<?= $this->escape($key); ?>]" value="<?= $this->escape($tab['page']); ?>" />
                        <input type="hidden" name="credit" value="<?= $this->escape($this->credit); ?>" />
                        <input type="hidden" name="date_from" value="<?= $this->escape($this->date_from); ?>" />
                        <input type="hidden" name="date_to" value="<?= $this->escape($this->date_to); ?>" />
                        <input type="hidden" name="date" value="<?= $this->escape($this->date) ?>" />
		        		<fieldset>
			        	<ul>
	                        <li class="gap">
	                            <div class="first"><label class="label_check2"><input type="checkbox" class="checkall" /></label></div>
                                <div class="first">&nbsp;</div>
	                            <div class="second"><h3><?= $this->proforma ? _t('Offerte') : _t('Factuur'); ?></h3></div>
	                            <div class="third"><h3><?= $this->proforma ? _t('Offerte') : _t('Factuur'); ?><?= _t('datum') ?></h3></div>
	                            <div class="five" style="width:15%;"><h3><?= _t('Debiteur') ?></h3></div>
                                <div class="four" style="width:33%;"><h3><?= _t('Geheugensteun') ?></h3></div>
	                            <div class="six"><h3><?= _t('Bedrag') ?></h3></div>
	                            <div class="seven"><h3><?= _t('Status') ?></h3></div>
	                        </li>   
	                        <?php foreach( $tab['result'] as $key => $invoice ): ?>
	                        <li <?= $key % 2 == 0 ? 'class="color"' : '' ?>>
	                            <div class="first"><label class="label_check2"><input type="checkbox" name="invoices[<?= $this->escape($invoice->id); ?>]" value="<?= $this->escape($invoice->id); ?>" /></label></div>
                                <div class="first">
                                    <?php if ( $invoice->from_webshop == 'yes'):?>
                                        <img src="/images/webshop/cart_icon.png" style="margin-top:5px;" />
                                    <?php endif; ?>
                                </div>
	                            <div class="second"><a href="<?= $this->baseUrl(); ?>/<?= $this->current_module ?>/index/view/id/<?= $this->escape($invoice->id); ?>"><?= $this->escape($invoice->number); ?></a></div>
	                            <div class="third"><?= $this->escape(date(Constants::DATE_FORMAT, $invoice->invoice_time)); ?></div>
	                            <div class="five" style="width:15%;"><a href="/contacts?contact_id=<?=$invoice->contact ? $invoice->contact->id : 0?>"><?= $invoice->contact ? $invoice->contact->company_name ? $invoice->contact->company_name : $invoice->contact->name : '' ?></a>&nbsp;</div>
                                <div class="four" style="width:33%;"><?= strip_tags($invoice->info); ?>&nbsp;</div>
	                            <div class="six"><div style="width:60px;margin-right:30px;text-align:left;"><nobr>&nbsp;&euro; <?= Utils::numberFormat($invoice->total_sum) ?></nobr></div></div>
	                            <div class="seven"><a class="concept <?= $this->escape($invoice->status_color) ?>" href="javascript:;" <?php if($invoice->status_text == 'Deels voldaan') echo 'title="Nog te ontvangen : &euro; '.Utils::numberFormat($invoice->unpaid_sum).'"'; ?>><?= $this->escape($invoice->status_text) ?></a></div>
	                        </li>
	                        <?php endforeach; ?>       
	                    </ul>           
	                    </fieldset>
	                    	                    
	                    </form>
                        </div>

                        <?= $this->paginate($tab['page'], $tab['total'], $tab['per_page'])->html('javascript:result_page({page});'); ?>
                    <?php elseif ( $this->is_new ): ?>
                        <div class="info" style="margin-bottom:10px;">
                            <span class="price"><?= $this->escape($tab['label']) ?> &nbsp;∙&nbsp; &euro; 0</span>
                        </div>

                        <div class="status" style="padding-bottom:1px;">
                        <form id="form-<?= $this->escape($key); ?>" method="get">                           
                        <fieldset>
                        <ul>
                            <li class="gap">
                                <div class="first"><label class="label_check2"><input type="checkbox" class="checkall" /></label></div>
                                <div class="first">&nbsp;</div>
                                <div class="second"><h3><?= $this->proforma ? _t('Offerte') : _t('Factuur'); ?></h3></div>
                                <div class="third"><h3><?= $this->proforma ? _t('Offerte') : _t('Factuur'); ?><?= _t('datum') ?></h3></div>
                                <div class="five" style="width:15%;"><h3><?= _t('Debiteur') ?></h3></div>
                                <div class="four" style="width:33%;"><h3><?= _t('Geheugensteun') ?></h3></div>
                                <div class="six"><h3><?= _t('Bedrag') ?></h3></div>
                                <div class="seven"><h3><?= _t('Status') ?></h3></div>
                            </li>                      
                        </ul>
                        <div style="padding: 15px 2%;">
                            <div style="float: left; width: 66%;">
                                <h3 style="font-size:19px;color:#599506; margin-bottom:10px;">Je eerste <?= $this->current_module=='offers' ? 'offerte' : 'factuur' ?> maken!</h3>
                                <span style="font-size:12px;">
                                <?php if ($this->current_module=='offers'): ?>
                                Start nu met het maken van uw eerste offerte. U zult ervaren hoe "SIMPEL" ons offertesysteem daadwerkelijk is.<br>
                                U voegt simpelweg een debiteur toe, een omschrijving om vervolgens te starten met de offerteregels.<br><br>
                                Uiteindelijk kiest u ervoor om de offerte te versturen per e-mail of gewoon zelf met de post.<br><br>
                                De klant zal de offerte moeten accepteren of weigeren. In beide gevallen zult u worden bericht hierover!<br><br>
                                Laten we beginnen!
                                <?php else: ?>
                                Start nu met het maken van uw eerste factuur.U zult ervaren hoe "SIMPEL" ons facturatiesysteem daadwerkelijk is.<br>
                                U voegt simpelweg een debiteur toe,een omschrijving om vervolgens te starten met de factuurregels.<br><br>
                                Uiteindelijk kiest u ervoor om de factuur te versturen per e-mail of gewoon zelf met de post.<br><br>
                                Laten we beginnen!
                                <?php endif; ?>
                                </span> <br>
                                <input type="button" class="green-button" name="first-new-invoice" onclick="document.location.href='/<?= $this->current_module=='offers' ? 'offers' : 'invoices' ?>/index/new';" value="<?= $this->current_module=='offers' ? 'Offerte' : 'Factuur' ?> maken!" style="margin-top: 10px;margin-bottom:20px;"/>
                            </div>
                            <div style="float: right; width: 25%;">
                                <img src="/images/<?= $this->current_module=='offers' ? 'offerte' : 'facturen' ?>.png" width="139px" alt="">
                            </div>
                        </div>
                        </fieldset>
                                                
                        </form>
                        </div>
                    <?php endif; ?>
		        	
	        	</div>
	        	
	        <?php endforeach; ?>
	    </div>                            
        <h2 style="margin-top: 10px;"><?= _t('Opties') ?></h2>
        
        <div class="search">
            
            <form id="main-invoice-form" action="" method="get">
                <fieldset class="drop" style="width:290px;">
                    <label style="margin-right:10px;"><?= _t('Bekijk') ?>:</label>

                    <select class="select" name="contact_id" onchange="window.location = baseUrl + '/<?= $this->escape($this->current_module) ?>/index/?contact_id=' + this.value">
                        <option value="0"><?= _t('Selecteer een debiteurengroep') ?></option>
                        <?php foreach( $this->contacts as $contact ): ?>
                        <option <?= $contact->id == $this->contact_id ? 'selected="selected"' : ''; ?> value="<?= $this->escape($contact->id); ?>"><?= $this->escape(trim($contact->firstname . ' ' . $contact->lastname)); ?></option>
                        <?php endforeach; ?>
                    </select>

                </fieldset>

                <fieldset class="drop" style="width:540px;">
                <label style="margin-right:10px;"><?= $this->proforma ? _t('Offerte') : ($this->credit ? _t('Credit-Factuur') : _t('Factuur')); ?><?= _t('datum') ?>:</label>
                <select name="date" onchange="$('#main-invoice-form').submit();">
                    <option value="0"><?= _t('Kiezen') ?></option>
                    <option value="last_month" <?= $this->date == 'last_month' ? 'selected="selected"' : ''; ?>><?= _t('Vorige maand') ?></option>
                    <option value="this_month" <?= $this->date == 'this_month' ? 'selected="selected"' : ''; ?>><?= _t('Huidige maand') ?></option>
                    <option value="last_quarter" <?= $this->date == 'last_quarter' ? 'selected="selected"' : ''; ?>><?= _t('Vorige kwartaal') ?></option>
                    <option value="this_quarter" <?= $this->date == 'this_quarter' ? 'selected="selected"' : ''; ?>><?= _t('Huidige kwartaal') ?></option>
                    <option value="last_year" <?= $this->date == 'last_year' ? 'selected="selected"' : ''; ?>><?= _t('Vorig jaar') ?></option>
                    <option value="this_year" <?= $this->date == 'this_year' ? 'selected="selected"' : ''; ?>><?= _t('Huidig jaar') ?></option>
                </select>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="text" onchange="$('#main-invoice-form').submit();" class="gray-input" style="width:68px;text-align: center;height:14px;vertical-align:bottom;" name="date_from" value="<?= $this->date_from; ?>" />
                <a style="line-height:26px;">-</a>
                <input type="text" onchange="$('#main-invoice-form').submit();" class="gray-input" style="width:68px;text-align: center;height:14px;vertical-align:bottom;" name="date_to" value="<?= $this->date_to; ?>" />
                </fieldset>

            <!--
            <?php if( !$this->proforma ): ?>
            <br style="clear:both;" />
            <p style="float:none;margin-top:5px;"><?= _t('Selecteer') ?> <?= $this->credit ? _t('credit-facturen') : _t('facturen') ?> om te <a id="markaspaid" href="#invoice-payment-dialog" style="color:#548C03;" href="javascript:;"><span><?= _t('markeren als betaald') ?></span></a></p>
            <?php endif; ?>
            -->

            </form>

        </div>
    </div>                                
</div>

<?= $this->partial('index/_partials/invoice-payment/dialog.phtml'); ?>

<script type="text/javascript">

    var active_tab = '<?= $this->escape($this->tab); ?>';
    var active_tab_init = true;
    $(document).ready(function(){
        $('#tabs').tabs();
        $('#tab-<?= $this->escape($this->tab); ?>').click();
        active_tab_init = false;
        $('[name=date_from], [name=date_to]').datepicker({dateFormat: "dd-mm-yy"});
        $('select[name="contact_id"]').combobox({input_class:'round-drop-down'});
        $('select[name="date"]').combobox({input_class:'round-drop-down'});
    });

    function set_active_tab(tab){
        disable_loader = true;
        active_tab = tab;
        if( active_tab_init == false ){
            $.get(baseUrl + '/invoices/index/active-tab/tab/' + tab);
        }
    }

    function result_page(page){
        $('[name="pages[' + active_tab + ']"]').val(page).parent('form').submit();
    }

</script>

<?= $this->partial('index/_partials/upload.phtml', array('proforma' => $this->proforma, 'credit' => $this->credit)); ?>
<script type="text/javascript">
    $('[name=date_from],[name=date_to]').attr('placeholder', 'dd-mm-jjjj');
</script>