<style type="text/css">

#report td {
    color: #333;
}

#report td h1 {
    font-size: 20px;
    line-height: 25px;
    font-weight: bold;
}
</style>

<table cellspacing="0" id="report" border="0">
    <colgroup>
        <col width="80px">
        <col width="90px">
        <col width="70px">
        <col width="130px">
        <col width="130px">
        <col width="150px">
    </colgroup>
    <tr>
        <td colspan="6" align="center" style="border:2px solid black"><h1>DAGOVERZICHT : <?=$this->curday?></h1></td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
        <td width="80px">
            <b>Verkoper :</b> 
        </td>
        <td colspan="2">
            <?=$this->emp_name?>
        </td>
        <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2">
            <b>Totale omzet : </b>
        </td>
        <td colspan="2" style="background-color:#BFBFBF;border:2px solid black;" align="center">&euro; <?= Utils::numberFormat($this->paidlist['sum'] + $this->openlist['sum']) ?></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr style="background-color:#BFBFBF;">
        <td width="80px;" align="center" style="border-left:2px solid black;border-top:2px solid black;border-bottom:2px solid black;"><b>Fac.Nummer</b></td>
        <td width="90px;" align="center" style="border-top:2px solid black;border-bottom:2px solid black;"><b>Naam klant</b></td>
        <td width="70px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;">&nbsp;</td>
        <td width="130px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;">&nbsp;</td>
        <td width="130px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;"><b>Factuur bedrag</b></td>
        <td width="150px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;border-right:2px solid black;"><b>Ontvangen bedrag</b></td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <!-- start paid list -->
    <?php if( $this->paidlist['result'] ): ?>
    <?php foreach( $this->paidlist['result'] as $key => $invoice ): ?>
    <tr>
        <td><?= $this->escape($invoice->number); ?></td>
        <td><?= $invoice->contact ? $invoice->contact->name : '' ?></td>
        <td colspan="2">&nbsp;</td>
        <td align="center"><nobr>&nbsp;&euro; <?= Utils::numberFormat($invoice->total_sum); ?></nobr></td>
        <td align="center"><nobr>&nbsp;&euro; <?= Utils::numberFormat($invoice->total_sum); ?></nobr></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <!-- end paid list -->
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3">&nbsp;</td>
        <td style="background-color: #BFBFBF;border-left:2px solid black;border-top:2px solid black;border-bottom:2px solid black;"><b>Totaal</b></td>
        <td style="background-color: #BFBFBF;border-top:2px solid black;border-bottom:2px solid black;" align="center"><nobr>&nbsp;&euro; <?=Utils::numberFormat($this->paidlist['sum'])?></nobr></td>
        <td style="background-color: #BFBFBF;border-right:2px solid black;border-top:2px solid black;border-bottom:2px solid black;" align="center"><nobr>&nbsp;&euro; <?=Utils::numberFormat($this->paidlist['sum'])?></nobr></td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2"><b>Cash ontvangen : </b></td>
        <td colspan="2" style="background-color:#56D723;border:2px solid black;" align="center"><nobr>&nbsp;&euro; <?=Utils::numberFormat($this->paidlist['sum'])?></nobr></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr style="background-color:#BFBFBF;">
        <td width="80px;" align="center" style="border-left:2px solid black;border-top:2px solid black;border-bottom:2px solid black;"><b>Fac.Nummer</b></td>
        <td width="90px;" align="center" style="border-top:2px solid black;border-bottom:2px solid black;"><b>Naam klant</b></td>
        <td width="70px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;">&nbsp;</td>
        <td width="130px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;"><b>Factuur bedrag</b></td>
        <td width="130px" align="center" style="border-top:2px solid black;border-bottom:2px solid black;"><b>Reeds ontvangen</b></td>
        <td width="150px" align="center" style="border-right:2px solid black;border-top:2px solid black;border-bottom:2px solid black;"><b>Nog te betalen</b></td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <!-- start open list -->
    <?php if( $this->openlist['result'] ): ?>    
    <?php foreach( $this->openlist['result'] as $key => $invoice ): ?>
    <tr>
        <td><?= $this->escape($invoice->number); ?></td>
        <td><?= $invoice->contact ? $invoice->contact->name : '' ?></td>
        <td>&nbsp;</td>
        <td align="center"><nobr>&nbsp;&euro; <?= Utils::numberFormat($invoice->total_sum); ?></nobr></td>
        <td align="center">&euro; 0.00</td>
        <td align="center"><nobr>&nbsp;&euro; <?= Utils::numberFormat($invoice->total_sum); ?></nobr></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <!-- end open list -->
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
        <td style="background-color: #BFBFBF;border-left:2px solid black;border-top:2px solid black;border-bottom:2px solid black;"><b>Totaal</b></td>
        <td style="background-color: #BFBFBF;border-top:2px solid black;border-bottom:2px solid black;" align="center">&euro; <?=Utils::numberFormat($this->openlist['sum'])?></td>
        <td style="background-color: #BFBFBF;border-top:2px solid black;border-bottom:2px solid black;" align="center">&euro; 0.00</td>
        <td style="background-color: #BFBFBF;border-right:2px solid black;border-top:2px solid black;border-bottom:2px solid black;" align="center">&euro; <?=Utils::numberFormat($this->openlist['sum'])?></td>
    </tr>
    <tr>
        <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2"><b>Overschrijving : </b></td>
        <td colspan="2" style="background-color:#ff0000;border:2px solid black;" align="center"><nobr>&nbsp;&euro; <?=Utils::numberFormat($this->openlist['sum'])?></nobr></td>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>