<style type="text/css">
#general td {
    color: #333;
    font-size: 13px;
}

#general td h1 {
    font-size: 19px;
    line-height: 25px;
    font-weight: bold;
}

#special td {
    color: #333;
    font-size: 13px;
}

#special td h1 {
    font-size: 19px;
    line-height: 25px;
    font-weight: bold;
}
</style>

<table cellspacing="0" id="general" border="0">
    <colgroup>
        <col width="90px">
        <col width="300px">
        <col width="170px">
        <col width="170px">
    </colgroup>
    <tr>
        <td colspan="4" align="center" style="border:2px solid #333"><h1>LAAD -& BESTELLIJST : <?=$this->curday?></h1></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <tr>
        <td width="90px">
            <b>Verkoper :</b> 
        </td>
        <td width="300px">
            <?=$this->emp_name?>
        </td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2" width="320px">&nbsp;</td>
        <td colspan="2" style="background-color:#BFBFBF;border-top:2px solid #333;border-left:2px solid #333;border-right:2px solid #333;" align="center"><b>AANTAL</b></td>
    </tr>
    <tr style="background-color:#BFBFBF;">
        <td width="90px;" align="center" style="border-left:2px solid #333;border-top:2px solid #333;border-bottom:2px solid #333;"><b>PROD. NR.</b></td>
        <td width="300px" style="border-top:2px solid #333;border-bottom:2px solid #333;"><b>OMSCHRIJVING</b></td>
        <td width="130px" align="center" style="border-left:2px solid #333;border-top:2px solid #333;border-bottom:2px solid #333;"><b>START</b></td>
        <td width="130px" align="center" style="border-left:2px solid #333;border-top:2px solid #333;border-bottom:2px solid #333;border-right:2px solid #333;"><b>VERKOCHT</b></td>
        <!--<td width="120px" align="center" style="border-left:2px solid #333;border-top:2px solid #333;border-bottom:2px solid #333;border-right:2px solid #333;"><b>EXTRA INLADEN</b></td>-->
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <!-- start general order list -->
    <?php if( $this->generallist ): ?>
    <?php foreach( $this->generallist as $row ): ?>
    <tr>
        <td align="center"><?=$this->escape($row['id']); ?></td>
        <td><?= $this->escape($row['name']) ?></td>
        <td align="center"><?php if ( empty($row['total']) ) {echo '0';} ?><?=$row['total']?></td>
        <td align="center"><?php if ( empty($row['snum']) ) {echo '0';} ?><?= $row['snum'] ?></td>
        <!--<td align="center"><?php //if ( empty($row['tnum']) ) {echo '0';} ?><?= $row['tnum'] ?></td>-->
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <!-- end paid list -->
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
</table>
<table cellspacing="0" id="special">
    <tr>
        <td width="90px">&nbsp;</td>
        <td width="160px">&nbsp;</td>
        <td width="150px">&nbsp;</td>
        <td width="260px">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2" style="background-color:#FF6600;border:2px solid #333;" align="center"><b>EXTRA BESTELLINGEN</b></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <tr style="background-color:#BFBFBF;">
        <td style="border-left:2px solid #333;border-top:2px solid #333;border-bottom:2px solid #333;"><b>PROD. NR.</b></td>
        <td colspan="2" style="border-top:2px solid #333;border-bottom:2px solid #333;"><b>OMSCHRIJVING</b></td>
        <td align="center" style="border:2px solid #333;"><b>AANTAL</b></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <!-- start open list -->
    <?php if( $this->speciallist ): ?>    
    <?php foreach( $this->speciallist as $key => $row ): ?>
    <tr>
        <td align="center"><?=$this->escape($row['id']); ?></td>
        <td colspan="2"><?= $this->escape($row['name']) ?></td>
        <td align="center"><?php if ( empty($row['tnum']) ) {echo '0';} ?><?= $row['tnum'] ?></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <!-- end open list -->
</table>