<?php include(APPLICATION_PATH . '/layouts/settings-sidebar.phtml'); ?>

<!-- START RIGHT -->
<div id="right">

    <!-- START OVERVIE -->
    <div class="oerview_Box1">

        <h2>Opties</h2>

        <div class="form">

            <form action="#">
                <fieldset>

                    <p>

                        <label>Titel</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Titel hier';}" onfocus="if(this.value == 'Titel hier') {this.value = '';}" value="Titel hier" class="field" />

                    </p>

                    <p>

                        <label>Adres</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Adres hier';}" onfocus="if(this.value == 'Adres hier') {this.value = '';}" value="Adres hier" class="field" />

                    </p>
                    <p>

                        <label>ABC Functie</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Fucntietitel';}" onfocus="if(this.value == 'Fucntietitel') {this.value = '';}" value="Fucntietitel" class="field" />

                    </p>
                    <p>

                        <label>Veiligheidcheck</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Titel hier';}" onfocus="if(this.value == 'Titel hier') {this.value = '';}" value="Titel hier" class="field" />

                    </p>

                </fieldset>

                <fieldset>

                    <p>

                        <label>Documenten</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Titel hier';}" onfocus="if(this.value == 'Titel hier') {this.value = '';}" value="Titel hier" class="field" />

                    </p>

                    <p>

                        <label>Projecten</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Adres hier';}" onfocus="if(this.value == 'Adres hier') {this.value = '';}" value="Adres hier" class="field" />

                    </p>
                    <p>

                        <label>Contacten</label>

                        <input type="text" onblur="if (this.value == '') {this.value = 'Fucntietitel';}" onfocus="if(this.value == 'Fucntietitel') {this.value = '';}" value="Fucntietitel" class="field" />

                    </p>

                    <input value="opslaan" class="btn" type="button" />

                </fieldset>
            </form>

        </div>

    </div>
    <!-- END OVERVIE -->

</div>
<!-- END RIGHT -->